/**
 * 汽车术语中英对照映射表
 * 覆盖常见车辆参数字段
 */

export const AUTO_TERM_MAP: Record<string, string> = {
  // 品牌/制造商
  "大众": "Volkswagen",
  "奥迪": "Audi",
  "宝马": "BMW",
  "奔驰": "Mercedes-Benz",
  "丰田": "Toyota",
  "本田": "Honda",
  "日产": "Nissan",
  "马自达": "Mazda",
  "斯巴鲁": "Subaru",
  "三菱": "Mitsubishi",
  "雷克萨斯": "Lexus",
  "英菲尼迪": "Infiniti",
  "讴歌": "Acura",
  "保时捷": "Porsche",
  "路虎": "Land Rover",
  "捷豹": "Jaguar",
  "沃尔沃": "Volvo",
  "萨博": "Saab",
  "斯柯达": "Skoda",
  "西雅特": "SEAT",
  "福特": "Ford",
  "雪佛兰": "Chevrolet",
  "别克": "Buick",
  "凯迪拉克": "Cadillac",
  "林肯": "Lincoln",
  "克莱斯勒": "Chrysler",
  "道奇": "Dodge",
  "吉普": "Jeep",
  "特斯拉": "Tesla",
  "比亚迪": "BYD",
  "吉利": "Geely",
  "长城": "Great Wall",
  "哈弗": "Haval",
  "长安": "Changan",
  "奇瑞": "Chery",
  "江淮": "JAC",
  "北汽": "BAIC",
  "上汽": "SAIC",
  "广汽": "GAC",
  "极氪": "Zeekr",
  "蔚来": "NIO",
  "小鹏": "XPeng",
  "理想": "Li Auto",
  "问界": "AITO",
  "阿维塔": "Avatr",
  "深蓝": "Deepal",
  "零跑": "Leapmotor",
  "哪吒": "Neta",
  "五菱": "Wuling",
  "宝骏": "Baojun",
  "领克": "Lynk & Co",
  "WEY": "WEY",
  "红旗": "Hongqi",
  "奔腾": "Besturn",
  "东风": "Dongfeng",
  "解放": "FAW",
  "重汽": "Sinotruk",
  "陕汽": "Shaanxi Auto",
  "福田": "Foton",
  "江铃": "JMC",
  "庆铃": "Qingling",
  "五十铃": "Isuzu",
  "现代": "Hyundai",
  "起亚": "Kia",
  "双龙": "SsangYong",
  "雷诺": "Renault",
  "标致": "Peugeot",
  "雪铁龙": "Citroen",
  "DS": "DS",
  "菲亚特": "Fiat",
  "阿尔法·罗密欧": "Alfa Romeo",
  "玛莎拉蒂": "Maserati",
  "法拉利": "Ferrari",
  "兰博基尼": "Lamborghini",
  "宾利": "Bentley",
  "劳斯莱斯": "Rolls-Royce",
  "阿斯顿·马丁": "Aston Martin",
  "迈凯伦": "McLaren",
  "MINI": "MINI",
  "smart": "smart",

  // 车身类型
  "SUV": "SUV",
  "轿车": "Sedan",
  "跑车": "Sports Car",
  "MPV": "MPV",
  "面包车": "Van",
  "皮卡": "Pickup",
  "越野车": "Off-road Vehicle",
  "大型SUV": "Large SUV",
  "中型SUV": "Mid-size SUV",
  "紧凑型SUV": "Compact SUV",
  "小型SUV": "Subcompact SUV",
  "大型轿车": "Large Sedan",
  "中型轿车": "Mid-size Sedan",
  "紧凑型轿车": "Compact Sedan",
  "小型轿车": "Subcompact Sedan",
  "微型车": "Micro Car",
  "两厢车": "Hatchback",
  "三厢车": "Sedan",
  "旅行车": "Wagon",
  "敞篷车": "Convertible",
  "硬顶敞篷": "Hardtop Convertible",
  "软顶敞篷": "Soft-top Convertible",
  "Coupe": "Coupe",
  "跨界车": "Crossover",

  // 燃料类型（VIN V4 power_type 字段，行业标准：英文全称 + 缩写）
  "纯电动": "Electric Vehicle (EV)",
  "电动": "Electric Vehicle (EV)",
  "BEV": "Electric Vehicle (EV)",
  "插电式混合动力": "Plug-in Hybrid Electric Vehicle (PHEV)",
  "插电混动": "Plug-in Hybrid Electric Vehicle (PHEV)",
  "插电式": "Plug-in Hybrid Electric Vehicle (PHEV)",
  "PHEV": "Plug-in Hybrid Electric Vehicle (PHEV)",
  "增程式混合动力": "Range-Extended Electric Vehicle (REEV)",
  "增程式": "Range-Extended Electric Vehicle (REEV)",
  "增程": "Range-Extended Electric Vehicle (REEV)",
  "REEV": "Range-Extended Electric Vehicle (REEV)",
  "EREV": "Range-Extended Electric Vehicle (REEV)",
  "油电混合动力": "Hybrid Electric Vehicle (HEV)",
  "油电混合": "Hybrid Electric Vehicle (HEV)",
  "混合动力": "Hybrid Electric Vehicle (HEV)",
  "油电混动": "Hybrid Electric Vehicle (HEV)",
  "HEV": "Hybrid Electric Vehicle (HEV)",
  "48V轻混合动力": "Mild Hybrid Electric Vehicle (MHEV)",
  "48V轻混": "Mild Hybrid Electric Vehicle (MHEV)",
  "轻混": "Mild Hybrid Electric Vehicle (MHEV)",
  "MHEV": "Mild Hybrid Electric Vehicle (MHEV)",
  "汽油": "Internal Combustion Engine-Gasoline (G-ICE)",
  "柴油": "Internal Combustion Engine-Diesel (D-ICE)",
  "天然气": "Compressed Natural Gas (CNG)",
  "液化石油气": "Liquefied Petroleum Gas (LPG)",
  "乙醇": "Ethanol",
  "氢燃料": "Hydrogen",
  "燃料电池": "Fuel Cell Electric Vehicle (FCEV)",
  "氢燃料电池": "Fuel Cell Electric Vehicle (FCEV)",
  "FCEV": "Fuel Cell Electric Vehicle (FCEV)",

  // 是否在售
  "是": "Yes",
  "否": "No",

  // 排放标准
  "国一": "China I",
  "国二": "China II",
  "国三": "China III",
  "国四": "China IV",
  "国五": "China V",
  "国六": "China VI",
  "欧一": "Euro 1",
  "欧二": "Euro 2",
  "欧三": "Euro 3",
  "欧四": "Euro 4",
  "欧五": "Euro 5",
  "欧六": "Euro 6",

  // 驱动方式（VIN V4 常见枚举）
  "前置前驱": "Front-engine Front-wheel Drive (FF)",
  "前置后驱": "Front-engine Rear-wheel Drive (FR)",
  "前置四驱": "Front-engine Four-wheel Drive (4WD)",
  "中置后驱": "Mid-engine Rear-wheel Drive (MR)",
  "中置四驱": "Mid-engine Four-wheel Drive",
  "后置后驱": "Rear-engine Rear-wheel Drive (RR)",
  "后置四驱": "Rear-engine Four-wheel Drive",
  "全时四驱": "Full-time 4WD",
  "分时四驱": "Part-time 4WD",
  "适时四驱": "On-demand 4WD",
  "前轮驱动": "Front-wheel Drive",
  "后轮驱动": "Rear-wheel Drive",
  "四轮驱动": "Four-wheel Drive",
  "双电机四驱": "Dual-motor 4WD",

  // 变速箱类型
  "手动": "Manual",
  "自动": "Automatic",
  "手自一体": "Tiptronic",
  "无级变速": "CVT",
  "无级": "CVT",
  "双离合": "DCT",
  "固定齿比": "Single-speed Fixed Gear",
  "电动车单速变速箱": "Single-speed EV Transmission",
  "AMT": "AMT",
  "混合动力专用变速箱(DHT)": "Dedicated Hybrid Transmission (DHT)",
  "1挡DHT": "1-speed DHT",
  "2挡DHT": "2-speed DHT",
  "3挡DHT": "3-speed DHT",

  // 车身数量 / 结构
  "三厢": "Three-box",
  "两厢": "Two-box (Hatchback)",

  // 车辆级别（VIN V4 枚举）
  "轿车类": "Sedan",
  "SUV类": "SUV",
  "MPV类": "MPV",
  "跑车类": "Sports Car",
  "皮卡类": "Pickup",
  "微面类": "Microvan",
  "轻客类": "Light Bus",
  "客车类": "Bus",
  "货车类": "Truck",
  "新能源轿车": "NEV Sedan",
  "新能源SUV": "NEV SUV",

  // 刹车类型
  "通风盘式": "Ventilated Disc",
  "盘式": "Disc",
  "鼓式": "Drum",
  "电子驻车": "Electronic Parking Brake",
  "手刹": "Hand Brake",
  "脚刹": "Foot Brake",

  // 车身结构
  "承载式": "Unibody",
  "非承载式": "Body-on-frame",

  // 燃油标号
  "92号": "92 Octane",
  "95号": "95 Octane",
  "98号": "98 Octane",
  "97号": "97 Octane",

  // 供油方式
  "直喷": "Direct Injection",
  "多点电喷": "Multi-point Injection",
  "混合喷射": "Hybrid Injection",
  "缸内直喷": "GDI",

  // 进口/国产
  "进口": "Import",
  "国产": "Domestic",

  // 机油相关
  "半合成": "Semi-synthetic",
  "全合成": "Fully Synthetic",
  "矿物油": "Mineral Oil",

  // 其他常用术语
  "涡轮增压": "Turbocharged",
  "自然吸气": "Naturally Aspirated",
  "机械增压": "Supercharged",
  "双增压": "Twin-charged",
  "涡轮增压+机械增压": "Turbo + Supercharged",

  // 常见车系名（高频命中，避免每次走 AI）
  "朗逸": "Lavida",
  "卡罗拉": "Corolla",
  "凯美瑞": "Camry",
  "雷凌": "Levin",
  "雅阁": "Accord",
  "思域": "Civic",
  "飞度": "Fit",
  "轩逸": "Sylphy",
  "天籁": "Teana",
  "奇骏": "X-Trail",
  "逍客": "Qashqai",
  "途观": "Tiguan",
  "帕萨特": "Passat",
  "迈腾": "Magotan",
  "速腾": "Sagitar",
  "宝来": "Bora",
  "高尔夫": "Golf",
  "桑塔纳": "Santana",
  "捷达": "Jetta",
  "英朗": "Excelle",
  "君威": "Regal",
  "君越": "LaCrosse",
  "威朗": "Verano",
  "福克斯": "Focus",
  "蒙迪欧": "Mondeo",
  "探险者": "Explorer",
  "牧马人": "Wrangler",
  "宋PLUS": "Song PLUS",
  "秦PLUS": "Qin PLUS",
  "海豹": "Seal",
  "海豚": "Dolphin",
  "理想L7": "Li L7",
  "理想L8": "Li L8",
  "理想L9": "Li L9",
};

/**
 * 品牌/厂商英文标准译法。
 * 命中该表则直接使用，不再走 AI；未命中仍交由 AI 兜底翻译。
 * 同时用于 brand（品牌）和 manufacturer（厂商）字段。
 */
export const BRAND_DICT: Record<string, string> = {
  "Audi Sport": "Audi",
  "DS汽车": "DS",
  "Jeep(进口)": "Jeep",
  "LEVC": "LEVC",
  "Polestar": "Polestar",
  "smart": "smart",
  "奥迪(进口)": "Audi",
  "阿维塔科技": "AVATR",
  "宝马(进口)": "BMW",
  "宝马M": "BMW",
  "保时捷": "Porsche",
  "北京奔驰": "Beijing Benz",
  "北京汽车": "BAIC",
  "北京汽车制造厂": "BAIC",
  "北汽新能源": "BAIC",
  "奔驰(进口)": "Mercedes-Benz",
  "宾利": "Bentley",
  "比亚迪": "BYD",
  "布加迪": "Bugatti",
  "曹操汽车": "Caocao",
  "长安福特": "Ford",
  "长安跨越": "Kuayue",
  "长安马自达": "Mazda",
  "长安轻型车": "Changan",
  "长安汽车": "Changan",
  "长安启源": "Qiyuan",
  "长城汽车": "GWM",
  "创维汽车": "Skyworth",
  "大运汽车": "Dayun",
  "大众(进口)": "Volkswagen",
  "大众汽车(安徽)": "Volkswagen",
  "电动屋": "EV House",
  "东风本田": "Dongfeng Honda",
  "东风乘用车": "Dongfeng",
  "东风风行": "Dongfeng Forthing",
  "东风汽车": "Dongfeng",
  "东风日产": "Dongfeng Nissan",
  "东风小康": "Dongfeng Sokon",
  "方程豹": "Formula Leopard",
  "法拉利": "Ferrari",
  "飞凡汽车": "Rising",
  "福田图雅诺": "Foton Toano",
  "广汽埃安新能源": "AION",
  "广汽本田": "GAC Honda",
  "广汽传祺": "GAC Trumpchi",
  "广汽丰田": "GAC Toyota",
  "光束汽车": "Spotlight",
  "豪驰智能": "Horche Intelligent",
  "恒驰": "Hengchi",
  "合创汽车": "HYCAN",
  "合众汽车": "Hozon Auto",
  "华晨宝马": "BMW Brilliance",
  "华晨新日": "Brilliance Xinri",
  "华人运通": "Human Horizons",
  "江淮汽车": "JAC Motors",
  "江铃福特": "JMC Ford",
  "江铃集团新能源": "JMC",
  "江铃汽车": "JMC",
  "江汽集团": "JAC",
  "嘉远汽车": "Jiayuan",
  "捷豹": "Jaguar",
  "捷尼赛思": "Genesis",
  "极氪": "ZEEKR",
  "极氪FR": "ZEEKR",
  "吉利几何": "Geely Geometry",
  "吉利汽车": "Geely",
  "吉利银河": "Geely Galaxy",
  "吉利远程": "Geely Farizon",
  "吉麦新能源": "LINGBOX",
  "凯迪拉克(进口)": "Cadillac",
  "开瑞汽车": "Karry Auto",
  "凯翼汽车": "COWIN",
  "开云汽车": "Kaiyun Motors",
  "克莱斯勒(进口)": "Chrysler",
  "科尼赛克": "Koenigsegg",
  "兰博基尼": "Lamborghini",
  "岚图汽车": "VOYAH",
  "劳斯莱斯": "Rolls-Royce",
  "雷达汽车": "RADAR",
  "雷克萨斯": "Lexus",
  "领克": "Lynk & Co",
  "零跑汽车": "Leapmotor",
  "领途汽车": "LinkTour",
  "理想汽车": "Li Auto",
  "罗伦士": "Lorinser",
  "路虎(进口)": "Land Rover",
  "路特斯": "Lotus",
  "迈凯伦": "McLaren",
  "玛莎拉蒂": "Maserati",
  "梅赛德斯-AMG": "Mercedes-AMG",
  "梅赛德斯-EQ": "Mercedes-EQ",
  "梅赛德斯-迈巴赫": "Mercedes-Maybach",
  "猛士科技": "M-Hero",
  "奇瑞捷豹路虎": "Chery Jaguar Land Rover",
  "奇瑞汽车": "Chery",
  "奇瑞新能源": "Chery",
  "起亚": "Kia",
  "起亚(进口)": "Kia",
  "瑞驰汽车": "Ruichi Auto",
  "睿蓝汽车": "Livan Auto",
  "赛力斯蓝电汽车": "Seres Landian Auto",
  "赛力斯汽车": "Seres Auto",
  "上汽奥迪": "SAIC Audi",
  "上汽大通": "SAIC Maxus",
  "上汽大众": "SAIC Volkswagen",
  "上汽集团": "SAIC Motor",
  "上汽通用别克": "SAIC-GM Buick",
  "上汽通用凯迪拉克": "SAIC-GM Cadillac",
  "上汽通用五菱": "SAIC-GM-Wuling",
  "上汽通用雪佛兰": "SAIC-GM Chevrolet",
  "厦门金旅": "Xiamen King Long",
  "深蓝汽车": "Deepal",
  "世极": "Toyota Century",
  "曙光汽车": "SG Auto",
  "腾势汽车": "Denza",
  "特斯拉(进口)": "Tesla",
  "特斯拉中国": "Tesla",
  "天际汽车": "Enovate Motors",
  "蔚来": "NIO",
  "威马汽车": "WM Motor",
  "沃尔沃(进口)": "Volvo",
  "沃尔沃亚太": "Volvo",
  "五菱工业": "Wuling",
  "五菱新能源": "Wuling",
  "现代N": "Hyundai",
  "小米汽车": "Xiaomi",
  "小跑车": "Xiaopaoche",
  "小鹏汽车": "XPENG",
  "星途": "Exeed",
  "鑫源汽车新能源": "SWM",
  "仰望": "Yangwang",
  "一汽-大众": "FAW-Volkswagen",
  "一汽奥迪": "FAW-Audi",
  "一汽奔腾": "FAW Bestune",
  "一汽丰田": "FAW Toyota",
  "一汽红旗": "Hongqi",
  "远航汽车": "Yuanhang",
  "云度新能源": "Yudo",
  "郑州日产": "Nissan",
  "知豆电动车": "Zhidou",
  "智己汽车": "IM",
  "鑫源汽车": "Shineray Automobile",
  "东南汽车": "Soueast Motor",
  "福田汽车": "Foton",
  "野马汽车": "Yema Auto",
  "中国重汽VGV": "SINOTRUK VGV",
  "中兴汽车": "ZXAUTO",
  "SWM斯威汽车": "SWM Motors",
  "北汽瑞翔": "BAIC Ruixiang",
  "新龙马汽车": "NLM MOTOR",
  "一汽-大众捷达": "Jetta",
  "九龙汽车": "JOYLONG",
  "力帆汽车": "Lifan",
  "沈阳金杯": "Shenyang Jinbei Automotive",
  "北汽福田时代祥菱": "Foton Xiangling",
  "成功汽车": "Victory Auto",
  "钧天机械": "JUN TIAN",
  "厦门金龙": "King Long",
  "北汽银翔": "BAIC Yinxiang",
  "比速汽车": "BISU",
  "二一二越野车": "212 Off-Road Vehicle",
  "观致汽车": "Qoros",
  "旅美房车": "Lvmei RV",
  "晓澳": "XIAOAO AUTOMOBILE",
  "雅升汽车": "YASHENG",
  "一汽海马": "FAW-Haima",
  "越界": "Yuejie",
  "浙江卡尔森": "Zhejiang Carlson",
  "众泰汽车": "Zotye",
  "荣威": "Roewe",
  "问界": "AITO",
  "智界": "Luxeed",
  "享界": "Stelato",
  "尊界": "Maextro",
  "尚界": "SAIC",
};

/**
 * 根据中文术语获取英文翻译
 * 如果映射表中没有，返回原文
 */
export function translateTerm(chinese: string): string {
  return AUTO_TERM_MAP[chinese] || chinese;
}

/**
 * 字段名称映射（中文标签 → 英文标签）
 */
// 英文小写 key 到英文字段名的映射（用于翻译 API）
export const FIELD_KEY_MAP: Record<string, string> = {
  "brand": "Brand",
  "typename": "Model Series",
  "name": "Model",
  "yeartype": "Year",
  "manufacturer": "Manufacturer",
  "price": "MSRP",
  "sizetype": "Vehicle Class",
  "bodytype": "Body Type",
  "listdate": "Launch Date",
  "stop_date": "Stop Date",
  "sale_state": "On Sale",
  "model": "Vehicle Model",
  "color": "Color",
  "enginemodel": "Engine Model",
  "engine": "Engine Model",
  "displacement": "Displacement",
  "maxpower": "Max Power",
  "fueltype": "Fuel Type",
  "fuelgrade": "Fuel Grade",
  "fuelmethod": "Fuel Injection",
  "environmentalstandards": "Emission Standard",
  "gearbox": "Transmission",
  "len": "Length",
  "width": "Width",
  "height": "Height",
  "wheelbase": "Wheel Base",
  "weight": "Curb Weight",
  "full_weight_max": "Gross Weight",
  "axes_num": "Axle Count",
  "track_front": "Front Track",
  "track_rear": "Rear Track",
  "seatnum": "Seat Count",
  "drivemode": "Drive Type",
  "groupname": "Group Name",
  "group_code": "Group Code",
  "remark": "Remark",
  "vin": "VIN",
};

export const FIELD_NAME_MAP: Record<string, string> = {
  "品牌": "Brand",
  "车系": "Model Series",
  "车型": "Model",
  "年款": "Year",
  "厂商": "Manufacturer",
  "指导价": "MSRP",
  "车辆级别": "Vehicle Class",
  "车身结构": "Body Type",
  "上市时间": "Launch Date",
  "是否进口": "Import Status",
  "VIN合规": "VIN Compliance",
  "发动机型号": "Engine Model",
  "排量": "Displacement",
  "进气形式": "Aspiration Type",
  "最大马力": "Max Horsepower",
  "最大功率": "Max Power",
  "最大扭矩": "Max Torque",
  "燃油类型": "Fuel Type",
  "燃油标号": "Fuel Grade",
  "供油方式": "Fuel Injection",
  "排放标准": "Emission Standard",
  "变速箱": "Transmission",
  "变速箱类型": "Transmission Type",
  "变速箱品牌": "Transmission Brand",
  "变速箱型号": "Transmission Model",
  "变速箱油容量": "Transmission Fluid Capacity",
  "长度": "Length",
  "宽度": "Width",
  "高度": "Height",
  "轴距": "Wheelbase",
  "整备质量": "Curb Weight",
  "座位数": "Seat Count",
  "车门数": "Door Count",
  "前轮胎规格": "Front Tire Size",
  "后轮胎规格": "Rear Tire Size",
  "前制动器": "Front Brake",
  "后制动器": "Rear Brake",
  "驻车制动": "Parking Brake",
  "机油容量": "Engine Oil Capacity",
  "推荐粘度": "Oil Viscosity",
  "机油等级": "Oil Grade",
  "机油类型": "Oil Type",
  "驱动方式": "Drive Type",
  "气缸数": "Cylinder Count",
  "燃料形式": "Fuel Type",
  "环保标准": "Emission Standard",
};
