import type { CustomsCodeItem } from './types';

/**
 * 运输方式代码（1位）
 */
export const TRANSPORT_MODES: CustomsCodeItem[] = [
  { code: '0', name: '非保税区', alias: 'fei baoshuiqu' },
  { code: '1', name: '监管仓库', alias: 'jianguan cangku' },
  { code: '2', name: '水路运输', alias: 'water transport shuilu yunshu shipping' },
  { code: '3', name: '铁路运输', alias: 'railway transport tielu yunshu' },
  { code: '4', name: '公路运输', alias: 'road transport gonglu yunshu truck' },
  { code: '5', name: '航空运输', alias: 'air transport hangkong yunshu' },
  { code: '6', name: '邮件运输', alias: 'mail transport youjian' },
  { code: '7', name: '保税区', alias: 'bonded zone baoshuiqu' },
  { code: '8', name: '保税仓库', alias: 'bonded warehouse baoshuicangku' },
  { code: '9', name: '其他运输', alias: 'other qita' },
  { code: 'W', name: '物流中心', alias: 'logistics center wuliu zhongxin' },
  { code: 'X', name: '物流园区', alias: 'logistics park wuliu yuanqu' },
  { code: 'Y', name: '保税港区', alias: 'bonded port baoshuigangqu' },
  { code: 'Z', name: '出口加工区', alias: 'export processing zone chukou jiagongqu' },
];

/**
 * 监管方式代码（4位）- 二手车出口相关
 */
export const SUPERVISION_MODES: CustomsCodeItem[] = [
  { code: '0110', name: '一般贸易', alias: 'general trade yiban maoyi' },
  { code: '0130', name: '易货贸易', alias: 'barter trade yihuo' },
  { code: '0214', name: '来料加工', alias: 'processing with materials lailiao jiagong' },
  { code: '0245', name: '来料料件内销', alias: 'lailiao neixiao' },
  { code: '0255', name: '来料深加工', alias: 'lailiao shenjiagong' },
  { code: '0258', name: '来料余料结转', alias: 'lailiao yuliao jiezhuan' },
  { code: '0265', name: '来料料件复出', alias: 'lailiao fuchu' },
  { code: '0300', name: '修理物品', alias: 'repair goods xiuli wupin' },
  { code: '0320', name: '修理物品(出境)', alias: 'repair outbound' },
  { code: '0400', name: '成套设备', alias: 'complete equipment chengtiao shebei' },
  { code: '0420', name: '加工贸易设备', alias: 'processing equipment jiagong maoyi shebei' },
  { code: '0500', name: '租赁不满一年', alias: 'lease <1year zulin' },
  { code: '0513', name: '补偿贸易', alias: 'compensation trade buchang maoyi' },
  { code: '0615', name: '进料对口', alias: 'jinliao duikou' },
  { code: '0654', name: '进料深加工', alias: 'jinliao shenjiagong' },
  { code: '0700', name: '进料料件退换', alias: 'jinliao tuihuan' },
  { code: '0715', name: '进料非对口', alias: 'jinliao feiduikou' },
  { code: '1110', name: '对台直接贸易', alias: 'taiwan trade' },
  { code: '1200', name: '保税间货物', alias: 'bonded goods' },
  { code: '1210', name: '保税电商', alias: 'bonded e-commerce baoshui dianshang' },
  { code: '1233', name: '保税仓库货物', alias: 'bonded warehouse goods' },
  { code: '1234', name: '保税区仓储转口', alias: 'bonded zone re-export' },
  { code: '1300', name: '修理物品(进出境)', alias: 'repair goods in/out' },
  { code: '1420', name: '来料加工设备', alias: 'processing equipment lailiao' },
  { code: '1500', name: '租赁征税', alias: 'lease duty zulin zhengshui' },
  { code: '1523', name: '租赁贸易', alias: 'lease trade zulin maoyi' },
  { code: '1616', name: '寄售代销', alias: 'consignment jishou daixiao' },
  { code: '1741', name: '免税品', alias: 'duty free goods mianshui pin' },
  { code: '1831', name: '外汇商品', alias: 'foreign exchange goods waihui shangpin' },
  { code: '2025', name: '展览品', alias: 'exhibition goods zhanlan pin' },
  { code: '2225', name: '一般贸易(外资设备)', alias: 'foreign investment' },
  { code: '2439', name: '免税外汇商品', alias: 'duty free forex goods' },
  { code: '2700', name: '出料加工', alias: 'outward processing chuliao jiagong' },
  { code: '2939', name: '出口加工区成品', alias: 'epz finished goods' },
  { code: '3010', name: '货样广告品A', alias: 'sample ad A huoyang guanggao' },
  { code: '3039', name: '货样广告品B', alias: 'sample ad B' },
  { code: '3100', name: '其他进出口免费', alias: 'other free qita mianfei' },
  { code: '3339', name: '其他贸易', alias: 'other trade qita maoyi' },
  { code: '3410', name: '承包工程进口', alias: 'contract import' },
  { code: '3422', name: '对外承包出口', alias: 'contract export duiwai chengbao' },
  { code: '3511', name: '援助物资', alias: 'aid materials yuanzhu wuzi' },
  { code: '3611', name: '无偿军援', alias: 'military aid wuchang junyuan' },
  { code: '3612', name: '捐赠物资', alias: 'donation juanzeng wuzi' },
  { code: '4019', name: '边境小额贸易', alias: 'border trade bianjing xiaoé' },
  { code: '4039', name: '对台小额贸易', alias: 'taiwan small trade' },
  { code: '4200', name: '驻外机构运回', alias: 'overseas institution return' },
  { code: '4539', name: '处理边境贸易物品', alias: 'border trade goods handling' },
  { code: '5010', name: '信汇贸易', alias: 'mail transfer' },
  { code: '5015', name: '特殊区域研发货物', alias: 'special zone r&d' },
  { code: '9610', name: '跨境电商零售', alias: 'cross-border e-commerce retail kuajing dianshang lingshou' },
  { code: '9710', name: '跨境电商B2B直接出口', alias: 'cross-border b2b direct export' },
  { code: '9739', name: '保税电商(海外仓)', alias: 'bonded e-commerce overseas warehouse' },
  { code: '9800', name: '租赁征税(新)', alias: 'lease duty new' },
  { code: '9900', name: '其他', alias: 'other qita' },
];

/**
 * 征免性质代码（3位）
 */
export const DUTY_NATURES: CustomsCodeItem[] = [
  { code: '101', name: '一般征税', alias: 'general duty yiban zhengshui' },
  { code: '118', name: '无偿援助', alias: 'free aid wuchang yuanzhu' },
  { code: '130', name: '残疾人', alias: 'disabled canjiren' },
  { code: '201', name: '无偿援助(无偿)', alias: 'aid free' },
  { code: '299', name: '其他法定', alias: 'other statutory qita fading' },
  { code: '301', name: '特定区域', alias: 'special zone teding quyu' },
  { code: '307', name: '保税区', alias: 'bonded zone baoshuiqu' },
  { code: '401', name: '科教用品', alias: 'scientific education kejiao yongpin' },
  { code: '403', name: '技术改造', alias: 'technical transformation jishu gaizao' },
  { code: '405', name: '综合利用', alias: 'comprehensive utilization zonghe liyong' },
  { code: '406', name: '海上石油', alias: 'offshore oil haishang shiyou' },
  { code: '407', name: '陆地石油', alias: 'land oil ludi shiyou' },
  { code: '409', name: '重大项目', alias: 'major project zhongda xiangmu' },
  { code: '412', name: '基础设施', alias: 'infrastructure jichu sheshi' },
  { code: '413', name: '残疾人自救', alias: 'disabled self-rescue' },
  { code: '417', name: '远洋渔业', alias: 'deep-sea fishery yuanyang yuye' },
  { code: '419', name: '其他公益性', alias: 'other public welfare qita gongyixing' },
  { code: '420', name: '船舶销售', alias: 'ship sales chuanbo xiaoshou' },
  { code: '422', name: '扶贫慈善', alias: 'poverty charity fupin cishan' },
  { code: '423', name: '航空器材', alias: 'aviation materials hangkong qicai' },
  { code: '501', name: '加工设备', alias: 'processing equipment jiagong shebei' },
  { code: '502', name: '来料加工', alias: 'processing with materials lailiao jiagong' },
  { code: '503', name: '进料加工', alias: 'processing with imports jinliao jiagong' },
  { code: '506', name: '边境小额', alias: 'border small bianjin xiaoé' },
  { code: '510', name: '港澳项目', alias: 'hk-macau project gangao xiangmu' },
  { code: '601', name: '中外合资', alias: 'sino-foreign joint venture zhongwai hezi' },
  { code: '602', name: '中外合作', alias: 'sino-foreign cooperation zhongwai hezuo' },
  { code: '603', name: '外资企业', alias: 'foreign-funded enterprise waizi qiye' },
  { code: '605', name: '勘探开发', alias: 'exploration kantan kaifa' },
  { code: '606', name: '贷款项目', alias: 'loan project daikuan xiangmu' },
  { code: '607', name: '勘探项目(海洋)', alias: 'offshore exploration' },
  { code: '608', name: '勘探项目(陆地)', alias: 'land exploration' },
  { code: '609', name: '贷款中标', alias: 'loan bid daikuan zhongbiao' },
  { code: '611', name: '国际组织', alias: 'international organization guoji zuzhi' },
  { code: '651', name: '加工贸易', alias: 'processing trade jiagong maoyi' },
  { code: '699', name: '公益性其他', alias: 'other public welfare' },
  { code: '789', name: '鼓励项目', alias: 'encouraged project guli xiangmu' },
  { code: '799', name: '自有资金', alias: 'own funds ziyou zijin' },
  { code: '801', name: '救灾捐赠', alias: 'disaster relief donation jiuzai juanzeng' },
  { code: '811', name: '抗灾救灾', alias: 'disaster relief kangzai jiuzai' },
  { code: '888', name: '航材包修', alias: 'aviation repair' },
  { code: '898', name: '免税', alias: 'duty free mianshui' },
  { code: '997', name: '自贸协定', alias: 'fta agreement zimao xieding' },
  { code: '998', name: '其他减免', alias: 'other reduction qita jianmian' },
  { code: '999', name: '其他法定', alias: 'other statutory qita fading' },
];

/**
 * 包装种类代码（1-2位）
 */
export const PACKAGE_TYPES: CustomsCodeItem[] = [
  { code: '1', name: '裸装', alias: 'nude luozhuang' },
  { code: '2', name: '散装', alias: 'bulk sanzhuang' },
  { code: '3', name: '托盘', alias: 'pallet tuopan' },
  { code: '4', name: '包', alias: 'bale bao' },
  { code: '5', name: '袋', alias: 'bag dai' },
  { code: '6', name: '桶', alias: 'drum tong' },
  { code: '7', name: '笼', alias: 'cage long' },
  { code: '8', name: '筐', alias: 'basket kuang' },
  { code: '9', name: '其他', alias: 'other qita' },
  { code: '10', name: '木箱', alias: 'wooden case muxiang' },
  { code: '11', name: '纸箱', alias: 'carton zhixiang' },
  { code: '12', name: '集装箱', alias: 'container jizhuangxiang' },
  { code: '13', name: '塑料箱', alias: 'plastic case suliaoxiang' },
  { code: '14', name: '金属桶', alias: 'metal drum jinshutong' },
  { code: '15', name: '塑料桶', alias: 'plastic drum suliaotong' },
  { code: '21', name: '胶合板箱', alias: 'plywood case jiaobanxiang' },
  { code: '22', name: '再生木托盘', alias: 'recycled wood pallet' },
  { code: '23', name: '塑料托盘', alias: 'plastic pallet' },
  { code: '31', name: '罐', alias: 'jar guan' },
  { code: '32', name: '瓶', alias: 'bottle ping' },
  { code: '33', name: '卷', alias: 'roll juan' },
  { code: '34', name: '捆', alias: 'bundle kun' },
  { code: '35', name: '件', alias: 'piece jian' },
  { code: '36', name: '提', alias: 'beverage carrier ti' },
  { code: '39', name: '软袋', alias: 'flexible bag ruandai' },
  { code: '40', name: '纺织袋', alias: 'woven bag fangzhi dai' },
  { code: '41', name: '纸塑复合袋', alias: 'paper-plastic bag' },
  { code: '42', name: '塑编袋', alias: 'pp woven bag subian dai' },
  { code: '99', name: '其他(未列名)', alias: 'other nes qita weilie' },
];

/**
 * 成交方式代码（1-2位）- Incoterms 对应
 */
export const INCOTERMS: CustomsCodeItem[] = [
  { code: '1', name: 'CIF', alias: 'cost insurance freight' },
  { code: '2', name: 'CFR', alias: 'cost and freight CNF C&F' },
  { code: '3', name: 'FOB', alias: 'free on board' },
  { code: '4', name: 'C&I', alias: 'cost and insurance' },
  { code: '5', name: 'EXW', alias: 'ex works' },
  { code: '6', name: 'FCA', alias: 'free carrier' },
  { code: '7', name: 'FAS', alias: 'free alongside ship' },
  { code: '8', name: 'CPT', alias: 'carriage paid to' },
  { code: '9', name: 'CIP', alias: 'carriage and insurance paid' },
  { code: '10', name: 'DAP', alias: 'delivered at place' },
  { code: '11', name: 'DPU', alias: 'delivered at place unloaded DAT' },
  { code: '12', name: 'DDP', alias: 'delivered duty paid' },
];

/**
 * 征减免税方式代码（1位）
 */
export const DUTY_EXEMPTIONS: CustomsCodeItem[] = [
  { code: '1', name: '照章征税', alias: 'pay duty as regulated zhaozhang zhengshui' },
  { code: '2', name: '折半征税', alias: 'half duty zheban zhengshui' },
  { code: '3', name: '全免', alias: 'full exemption quanmian' },
  { code: '4', name: '特案减免', alias: 'special case reduction tean jianmian' },
  { code: '5', name: '随征免性质', alias: 'follow duty nature suizheng mianxingzhi' },
  { code: '6', name: '保证金', alias: 'deposit baozhengjin' },
  { code: '7', name: '保函', alias: 'letter of guarantee baohan' },
  { code: '8', name: '折半补税', alias: 'half duty supplement' },
  { code: '9', name: '出口全额退税', alias: 'export full refund chukou quané tuishui' },
];

/**
 * 法定计量单位代码（3位）- 常用
 */
export const UNITS: CustomsCodeItem[] = [
  { code: '001', name: '辆', alias: 'vehicle liang unit' },
  { code: '002', name: '座', alias: 'seat zuo' },
  { code: '003', name: '架', alias: 'frame jia' },
  { code: '004', name: '艘', alias: 'vessel sou' },
  { code: '005', name: '个', alias: 'piece ge' },
  { code: '006', name: '件', alias: 'item jian' },
  { code: '007', name: '套', alias: 'set tao' },
  { code: '008', name: '台', alias: 'unit tai' },
  { code: '009', name: '只', alias: 'piece zhi' },
  { code: '010', name: '头', alias: 'head tou' },
  { code: '030', name: '台(套)', alias: 'set unit' },
  { code: '033', name: '千瓦', alias: 'kilowatt qianwa kW' },
  { code: '034', name: '千瓦时', alias: 'kilowatt hour qianwashi kWh' },
  { code: '035', name: '千克', alias: 'kilogram qianke kg' },
  { code: '036', name: '百千克', alias: '100kg baiqianke' },
  { code: '037', name: '吨', alias: 'ton dun t' },
  { code: '038', name: '万吨', alias: '10k tons wandun' },
  { code: '039', name: '升', alias: 'liter sheng L' },
  { code: '040', name: '毫升', alias: 'milliliter haosheng mL' },
  { code: '041', name: '米', alias: 'meter mi m' },
  { code: '042', name: '千米', alias: 'kilometer qianmi km' },
  { code: '043', name: '厘米', alias: 'centimeter limi cm' },
  { code: '044', name: '毫米', alias: 'millimeter haomi mm' },
  { code: '045', name: '平方米', alias: 'square meter pingfangmi m2' },
  { code: '046', name: '立方米', alias: 'cubic meter lifangmi m3' },
  { code: '047', name: '平方英尺', alias: 'square foot' },
  { code: '048', name: '立方英尺', alias: 'cubic foot' },
  { code: '049', name: '码', alias: 'yard ma' },
  { code: '050', name: '英尺', alias: 'foot yingchi' },
  { code: '051', name: '英寸', alias: 'inch yingcun' },
  { code: '052', name: '蒲式耳', alias: 'bushel pusher' },
  { code: '053', name: '公吨', alias: 'metric ton gongdun' },
  { code: '054', name: '长吨', alias: 'long ton changdun' },
  { code: '055', name: '短吨', alias: 'short ton duandun' },
  { code: '056', name: '加仑', alias: 'gallon jialun' },
  { code: '057', name: '千升', alias: 'kiloliter qiansheng kL' },
  { code: '058', name: '百升', alias: 'hectoliter baisheng hL' },
  { code: '059', name: '千只', alias: '1k pieces qianzhi' },
  { code: '060', name: '千件', alias: '1k items qianjian' },
  { code: '061', name: '千架', alias: '1k frames qianjia' },
  { code: '062', name: '千辆', alias: '1k vehicles qianliang' },
  { code: '067', name: '千瓦时(度)', alias: 'kWh du' },
  { code: '068', name: '千升桶', alias: '1k liter barrel' },
  { code: '071', name: '千瓦时(计费)', alias: 'billed kWh' },
  { code: '072', name: '百万瓦', alias: 'megawatt baiwanwa MW' },
  { code: '073', name: '千兆瓦', alias: 'gigawatt qianzhaowa GW' },
  { code: '098', name: '百万贝可', alias: 'MBq' },
  { code: '100', name: '克拉', alias: 'carat kela ct' },
  { code: '101', name: '安培', alias: 'ampere anpei A' },
  { code: '102', name: '千伏安', alias: 'kilovolt-ampere qianfuan kVA' },
  { code: '103', name: '千瓦(功率)', alias: 'kilowatt gonglü' },
  { code: '108', name: '对', alias: 'pair dui' },
  { code: '109', name: '批', alias: 'batch pi' },
  { code: '110', name: '盘', alias: 'tray pan' },
  { code: '111', name: '打', alias: 'dozen da' },
  { code: '112', name: '罗', alias: 'gross luo' },
  { code: '113', name: '令', alias: 'ream ling' },
  { code: '114', name: '卷(匹)', alias: 'roll pi' },
  { code: '115', name: '盒', alias: 'box he' },
  { code: '116', name: '箱', alias: 'case xiang' },
  { code: '118', name: '桶(化工)', alias: 'barrel tong' },
  { code: '120', name: '张', alias: 'sheet zhang' },
  { code: '122', name: '个(罐)', alias: 'can ge' },
  { code: '123', name: '听', alias: 'tin ting' },
  { code: '124', name: '瓶', alias: 'bottle ping' },
  { code: '125', name: '罐', alias: 'tin can guan' },
  { code: '126', name: '包', alias: 'pack bao' },
  { code: '128', name: '捆', alias: 'bundle kun' },
  { code: '130', name: '提', alias: 'carry ti' },
  { code: '131', name: '打(瓶)', alias: 'dozen bottle' },
  { code: '132', name: '版', alias: 'block ban' },
  { code: '134', name: '串', alias: 'string chuan' },
  { code: '135', name: '枚', alias: 'piece mei' },
  { code: '136', name: '袋', alias: 'bag dai' },
  { code: '139', name: '粒', alias: 'grain li' },
  { code: '140', name: '盒(小)', alias: 'small box' },
  { code: '142', name: '万粒', alias: '10k grains wanli' },
  { code: '151', name: '万只', alias: '10k pieces wanzhi' },
  { code: '152', name: '万套', alias: '10k sets wantao' },
  { code: '153', name: '万头', alias: '10k heads wantou' },
  { code: '154', name: '万张', alias: '10k sheets wanzhang' },
  { code: '159', name: '千伏', alias: 'kilovolt qianfu kV' },
  { code: '161', name: '千瓦时(计费)', alias: 'billed kWh 2' },
  { code: '163', name: '亿个', alias: '100m pieces yige' },
  { code: '164', name: '亿支', alias: '100m pieces yizhi' },
  { code: '165', name: '亿粒', alias: '100m grains yili' },
  { code: '166', name: '亿片', alias: '100m slices yipian' },
  { code: '167', name: '亿瓦', alias: '100m watts yiwa' },
  { code: '185', name: '千克(净重)', alias: 'kg net jingzhong' },
  { code: '201', name: '手', alias: 'hand shou' },
  { code: '203', name: '双', alias: 'pair shuang' },
  { code: '207', name: '千双', alias: '1k pairs qianshuang' },
  { code: '217', name: '万双', alias: '10k pairs wanshuang' },
  { code: '221', name: '把', alias: 'handle ba' },
  { code: '222', name: '百把', alias: '100 handles baiba' },
  { code: '223', name: '千把', alias: '1k handles qianba' },
  { code: '224', name: '万把', alias: '10k handles wanba' },
  { code: '231', name: '顶', alias: 'top ding' },
  { code: '233', name: '条', alias: 'strip tiao' },
  { code: '234', name: '千条', alias: '1k strips qiantiao' },
  { code: '235', name: '万条', alias: '10k strips wantiao' },
  { code: '237', name: '枚(徽章)', alias: 'badge mei' },
  { code: '239', name: '副', alias: 'pair fu' },
  { code: '243', name: '千副', alias: '1k pairs qianfu' },
  { code: '245', name: '万副', alias: '10k pairs wanfu' },
  { code: '247', name: '部', alias: 'unit bu' },
  { code: '249', name: '千部', alias: '1k units qianbu' },
  { code: '251', name: '万部', alias: '10k units wanbu' },
  { code: '253', name: '支', alias: 'branch zhi' },
  { code: '255', name: '千支', alias: '1k branches qianzhi' },
  { code: '257', name: '万支', alias: '10k branches wanzhi' },
  { code: '259', name: '本', alias: 'book ben' },
  { code: '261', name: '千本', alias: '1k books qianben' },
  { code: '263', name: '万本', alias: '10k books wanben' },
  { code: '265', name: '卷', alias: 'roll juan' },
  { code: '267', name: '千卷', alias: '1k rolls qianjuan' },
  { code: '269', name: '万卷', alias: '10k rolls wanjuan' },
  { code: '311', name: '辆(二轮)', alias: 'motorcycle liang' },
  { code: '312', name: '辆(三轮)', alias: 'tricycle liang' },
];
