import type { CustomsCodeItem } from './types';

/**
 * 国别（地区）代码 - ISO 3166-1 alpha-3，二手车出口主要目的地
 * 数据来源：海关《国别（地区）代码表》
 */
export const COUNTRIES: CustomsCodeItem[] = [
  // 亚洲
  { code: 'CHN', name: '中国', alias: 'china zhongguo' },
  { code: 'HKG', name: '中国香港', alias: 'hongkong xianggang' },
  { code: 'MAC', name: '中国澳门', alias: 'macao aomen' },
  { code: 'TWN', name: '中国台湾', alias: 'taiwan' },
  { code: 'JPN', name: '日本', alias: 'japan riben' },
  { code: 'KOR', name: '韩国', alias: 'korea hanguo' },
  { code: 'PRK', name: '朝鲜', alias: 'north korea chaoxian' },
  { code: 'MNG', name: '蒙古', alias: 'mongolia menggu' },
  { code: 'VNM', name: '越南', alias: 'vietnam yuenan' },
  { code: 'LAO', name: '老挝', alias: 'laos laowo' },
  { code: 'KHM', name: '柬埔寨', alias: 'cambodia jianpuzhai' },
  { code: 'THA', name: '泰国', alias: 'thailand taiguo' },
  { code: 'MMR', name: '缅甸', alias: 'myanmar miandian' },
  { code: 'MYS', name: '马来西亚', alias: 'malaysia malaixiya' },
  { code: 'SGP', name: '新加坡', alias: 'singapore xinjiapo' },
  { code: 'IDN', name: '印度尼西亚', alias: 'indonesia yinni' },
  { code: 'BRN', name: '文莱', alias: 'brunei wenlai' },
  { code: 'PHL', name: '菲律宾', alias: 'philippines feilvbin' },
  { code: 'TLS', name: '东帝汶', alias: 'timor' },
  { code: 'IND', name: '印度', alias: 'india yindu' },
  { code: 'PAK', name: '巴基斯坦', alias: 'pakistan bajisitan' },
  { code: 'BGD', name: '孟加拉国', alias: 'bangladesh mengjiala' },
  { code: 'LKA', name: '斯里兰卡', alias: 'sri lanka' },
  { code: 'NPL', name: '尼泊尔', alias: 'nepal niboer' },
  { code: 'BTN', name: '不丹', alias: 'bhutan budan' },
  { code: 'MDV', name: '马尔代夫', alias: 'maldives maerdaifu' },
  { code: 'KAZ', name: '哈萨克斯坦', alias: 'kazakhstan hasakesitan' },
  { code: 'KGZ', name: '吉尔吉斯斯坦', alias: 'kyrgyzstan' },
  { code: 'TJK', name: '塔吉克斯坦', alias: 'tajikistan' },
  { code: 'UZB', name: '乌兹别克斯坦', alias: 'uzbekistan' },
  { code: 'TKM', name: '土库曼斯坦', alias: 'turkmenistan' },
  { code: 'AFG', name: '阿富汗', alias: 'afghanistan afuhan' },
  { code: 'IRN', name: '伊朗', alias: 'iran yilang' },
  { code: 'IRQ', name: '伊拉克', alias: 'iraq yilake' },
  { code: 'KWT', name: '科威特', alias: 'kuwait keweite' },
  { code: 'SAU', name: '沙特阿拉伯', alias: 'saudi arabia shate' },
  { code: 'BHR', name: '巴林', alias: 'bahrain balin' },
  { code: 'QAT', name: '卡塔尔', alias: 'qatar kataer' },
  { code: 'ARE', name: '阿联酋', alias: 'uae united arab emirates' },
  { code: 'OMN', name: '阿曼', alias: 'oman aman' },
  { code: 'YEM', name: '也门', alias: 'yemen yemen' },
  { code: 'SYR', name: '叙利亚', alias: 'syria xuliya' },
  { code: 'LBN', name: '黎巴嫩', alias: 'lebanon libanen' },
  { code: 'JOR', name: '约旦', alias: 'jordan yuedan' },
  { code: 'ISR', name: '以色列', alias: 'israel yiselie' },
  { code: 'PSE', name: '巴勒斯坦', alias: 'palestine balesitan' },
  { code: 'TUR', name: '土耳其', alias: 'turkey tuerqi' },
  { code: 'CYP', name: '塞浦路斯', alias: 'cyprus saipulusi' },
  // 欧洲
  { code: 'FIN', name: '芬兰', alias: 'finland fenlan' },
  { code: 'SWE', name: '瑞典', alias: 'sweden ruidian' },
  { code: 'NOR', name: '挪威', alias: 'norway nuowei' },
  { code: 'ISL', name: '冰岛', alias: 'iceland bingdao' },
  { code: 'DNK', name: '丹麦', alias: 'denmark maimai' },
  { code: 'EST', name: '爱沙尼亚', alias: 'estonia aishaniya' },
  { code: 'LVA', name: '拉脱维亚', alias: 'latvia latuoweiya' },
  { code: 'LTU', name: '立陶宛', alias: 'lithuanian litaowan' },
  { code: 'RUS', name: '俄罗斯联邦', alias: 'russia eluosi' },
  { code: 'BLR', name: '白俄罗斯', alias: 'belarus baieluosi' },
  { code: 'UKR', name: '乌克兰', alias: 'ukraine wukelan' },
  { code: 'MDA', name: '摩尔多瓦', alias: 'moldova moerduowa' },
  { code: 'POL', name: '波兰', alias: 'poland bolan' },
  { code: 'CZE', name: '捷克', alias: 'czech jieke' },
  { code: 'SVK', name: '斯洛伐克', alias: 'slovakia siluofake' },
  { code: 'HUN', name: '匈牙利', alias: 'hungary xiongyali' },
  { code: 'DEU', name: '德国', alias: 'germany deguo' },
  { code: 'AUT', name: '奥地利', alias: 'austria aodili' },
  { code: 'CHE', name: '瑞士', alias: 'switzerland ruishi' },
  { code: 'LIE', name: '列支敦士登', alias: 'liechtenstein' },
  { code: 'GBR', name: '英国', alias: 'uk united kingdom yingguo' },
  { code: 'IRL', name: '爱尔兰', alias: 'ireland aierlan' },
  { code: 'NLD', name: '荷兰', alias: 'netherlands helan' },
  { code: 'BEL', name: '比利时', alias: 'belgium bilishi' },
  { code: 'LUX', name: '卢森堡', alias: 'luxembourg lusenbao' },
  { code: 'FRA', name: '法国', alias: 'france faguo' },
  { code: 'MCO', name: '摩纳哥', alias: 'monaco monage' },
  { code: 'ESP', name: '西班牙', alias: 'spain xibanya' },
  { code: 'PRT', name: '葡萄牙', alias: 'portugal putaoya' },
  { code: 'AND', name: '安道尔', alias: 'andorra andaoer' },
  { code: 'ITA', name: '意大利', alias: 'italy yidali' },
  { code: 'VAT', name: '梵蒂冈', alias: 'vatican fandigang' },
  { code: 'SMR', name: '圣马力诺', alias: 'san marino' },
  { code: 'MLT', name: '马耳他', alias: 'malta maerta' },
  { code: 'HRV', name: '克罗地亚', alias: 'croatia' },
  { code: 'SVN', name: '斯洛文尼亚', alias: 'slovenia' },
  { code: 'BIH', name: '波黑', alias: 'bosnia' },
  { code: 'SRB', name: '塞尔维亚', alias: 'serbia saierweiya' },
  { code: 'MNE', name: '黑山', alias: 'montenegro heishan' },
  { code: 'MKD', name: '北马其顿', alias: 'north macedonia' },
  { code: 'ALB', name: '阿尔巴尼亚', alias: 'albania' },
  { code: 'GRC', name: '希腊', alias: 'greece xila' },
  { code: 'ROU', name: '罗马尼亚', alias: 'romania' },
  { code: 'BGR', name: '保加利亚', alias: 'bulgaria baojialiya' },
  // 非洲
  { code: 'EGY', name: '埃及', alias: 'egypt aiji' },
  { code: 'LBY', name: '利比亚', alias: 'libya libiya' },
  { code: 'TUN', name: '突尼斯', alias: 'tunisia tunisi' },
  { code: 'DZA', name: '阿尔及利亚', alias: 'algeria' },
  { code: 'MAR', name: '摩洛哥', alias: 'morocco moluoge' },
  { code: 'SDN', name: '苏丹', alias: 'sudan sudan' },
  { code: 'SSD', name: '南苏丹', alias: 'south sudan' },
  { code: 'ETH', name: '埃塞俄比亚', alias: 'ethiopia' },
  { code: 'ERI', name: '厄立特里亚', alias: 'eritrea' },
  { code: 'DJI', name: '吉布提', alias: 'djibouti jibuti' },
  { code: 'SOM', name: '索马里', alias: 'somalia suomali' },
  { code: 'KEN', name: '肯尼亚', alias: 'kenya kenniya' },
  { code: 'UGA', name: '乌干达', alias: 'uganda wuganda' },
  { code: 'TZA', name: '坦桑尼亚', alias: 'tanzania tansangniya' },
  { code: 'RWA', name: '卢旺达', alias: 'rwanda' },
  { code: 'BDI', name: '布隆迪', alias: 'burundi' },
  { code: 'COD', name: '刚果(金)', alias: 'drc congo' },
  { code: 'COG', name: '刚果(布)', alias: 'republic of congo' },
  { code: 'CAF', name: '中非', alias: 'central africa zhongfei' },
  { code: 'TCD', name: '乍得', alias: 'chad zhade' },
  { code: 'CMR', name: '喀麦隆', alias: 'cameroon' },
  { code: 'NGA', name: '尼日利亚', alias: 'nigeria niriliya' },
  { code: 'NER', name: '尼日尔', alias: 'niger' },
  { code: 'BEN', name: '贝宁', alias: 'benin beining' },
  { code: 'TGO', name: '多哥', alias: 'togo' },
  { code: 'GHA', name: '加纳', alias: 'ghana jiana' },
  { code: 'CIV', name: '科特迪瓦', alias: 'ivory coast ketediwa' },
  { code: 'LBR', name: '利比里亚', alias: 'liberia' },
  { code: 'SLE', name: '塞拉利昂', alias: 'sierra leone' },
  { code: 'GIN', name: '几内亚', alias: 'guinea jineiya' },
  { code: 'GNB', name: '几内亚比绍', alias: 'guinea-bissau' },
  { code: 'SEN', name: '塞内加尔', alias: 'senegal saineijiaer' },
  { code: 'GMB', name: '冈比亚', alias: 'gambia' },
  { code: 'MLI', name: '马里', alias: 'mali mali' },
  { code: 'BFA', name: '布基纳法索', alias: 'burkina faso' },
  { code: 'CPV', name: '佛得角', alias: 'cape verde' },
  { code: 'MRT', name: '毛里塔尼亚', alias: 'mauritania' },
  { code: 'SEN', name: '塞内加尔', alias: 'senegal' },
  { code: 'GAB', name: '加蓬', alias: 'gabon jiapeng' },
  { code: 'GNQ', name: '赤道几内亚', alias: 'equatorial guinea' },
  { code: 'AGO', name: '安哥拉', alias: 'angola angele' },
  { code: 'ZMB', name: '赞比亚', alias: 'zambia zanbiya' },
  { code: 'MWI', name: '马拉维', alias: 'malawi malawei' },
  { code: 'MOZ', name: '莫桑比克', alias: 'mozambique mosangbike' },
  { code: 'ZWE', name: '津巴布韦', alias: 'zimbabwe jinbabuwei' },
  { code: 'BWA', name: '博茨瓦纳', alias: 'botswana bociwana' },
  { code: 'NAM', name: '纳米比亚', alias: 'namibia' },
  { code: 'ZAF', name: '南非', alias: 'south africa nanfei' },
  { code: 'LSO', name: '莱索托', alias: 'lesotho' },
  { code: 'SWZ', name: '斯威士兰', alias: 'eswatini' },
  { code: 'MDG', name: '马达加斯加', alias: 'madagascar' },
  { code: 'SYC', name: '塞舌尔', alias: 'seychelles' },
  { code: 'MUS', name: '毛里求斯', alias: 'mauritius' },
  { code: 'COM', name: '科摩罗', alias: 'comoros' },
  // 美洲
  { code: 'CAN', name: '加拿大', alias: 'canada jianada' },
  { code: 'USA', name: '美国', alias: 'united states meiguo' },
  { code: 'MEX', name: '墨西哥', alias: 'mexico moxige' },
  { code: 'GTM', name: '危地马拉', alias: 'guatemala' },
  { code: 'BLZ', name: '伯利兹', alias: 'belize' },
  { code: 'SLV', name: '萨尔瓦多', alias: 'el salvador' },
  { code: 'HND', name: '洪都拉斯', alias: 'honduras hongdulasi' },
  { code: 'NIC', name: '尼加拉瓜', alias: 'nicaragua' },
  { code: 'CRI', name: '哥斯达黎加', alias: 'costa rica' },
  { code: 'PAN', name: '巴拿马', alias: 'panama banama' },
  { code: 'CUB', name: '古巴', alias: 'cuba guba' },
  { code: 'JAM', name: '牙买加', alias: 'jamaica yamaijia' },
  { code: 'HTI', name: '海地', alias: 'haiti haidi' },
  { code: 'DOM', name: '多米尼加', alias: 'dominican duominijia' },
  { code: 'PRI', name: '波多黎各', alias: 'puerto rico' },
  { code: 'BHS', name: '巴哈马', alias: 'bahamas' },
  { code: 'BRB', name: '巴巴多斯', alias: 'barbados' },
  { code: 'TTO', name: '特立尼达和多巴哥', alias: 'trinidad' },
  { code: 'COL', name: '哥伦比亚', alias: 'colombia gelunbiya' },
  { code: 'VEN', name: '委内瑞拉', alias: 'venezuela weineiruila' },
  { code: 'GUY', name: '圭亚那', alias: 'guyana' },
  { code: 'SUR', name: '苏里南', alias: 'suriname' },
  { code: 'ECU', name: '厄瓜多尔', alias: 'ecuador eguaduoer' },
  { code: 'PER', name: '秘鲁', alias: 'peru milu' },
  { code: 'BRA', name: '巴西', alias: 'brazil baxi' },
  { code: 'CHL', name: '智利', alias: 'chile zhili' },
  { code: 'ARG', name: '阿根廷', alias: 'argentian agenting' },
  { code: 'URY', name: '乌拉圭', alias: 'uruguay wulagui' },
  { code: 'PRY', name: '巴拉圭', alias: 'paraguay balagui' },
  { code: 'BOL', name: '玻利维亚', alias: 'bolivia boliweiya' },
  // 大洋洲
  { code: 'AUS', name: '澳大利亚', alias: 'australia aodaliya' },
  { code: 'NZL', name: '新西兰', alias: 'new zealand xinxilan' },
  { code: 'PNG', name: '巴布亚新几内亚', alias: 'papua new guinea' },
  { code: 'FJI', name: '斐济', alias: 'fiji feiji' },
  { code: 'SLB', name: '所罗门群岛', alias: 'solomon islands' },
  { code: 'VUT', name: '瓦努阿图', alias: 'vanuatu' },
  { code: 'NCL', name: '新喀里多尼亚', alias: 'new caledonia' },
  { code: 'PYF', name: '法属波利尼西亚', alias: 'french polynesia' },
  { code: 'WSM', name: '萨摩亚', alias: 'samoa' },
  { code: 'TON', name: '汤加', alias: 'tonga tangjia' },
];
