import type { CustomsCodeItem } from './types';

/**
 * 币制代码（3位数字）- ISO 4217 数字代码
 * 数据来源：海关《币制代码表》
 */
export const CURRENCIES: CustomsCodeItem[] = [
  { code: '142', name: '人民币', alias: 'CNY RMB renminbi yuan' },
  { code: '502', name: '美元', alias: 'USD US dollar meiyuan' },
  { code: '300', name: '欧元', alias: 'EUR euro ouyuan' },
  { code: '303', name: '英镑', alias: 'GBP british pound yingbang' },
  { code: '116', name: '日元', alias: 'JPY japanese yen riyuan' },
  { code: '133', name: '韩元', alias: 'KRW won hanyuan' },
  { code: '110', name: '港币', alias: 'HKD hong kong dollar' },
  { code: '121', name: '澳门元', alias: 'MOP pataca aomenyuan' },
  { code: '143', name: '新台币', alias: 'TWD taiwan dollar' },
  { code: '331', name: '瑞士法郎', alias: 'CHF swiss franc ruishi falang' },
  { code: '302', name: '丹麦克朗', alias: 'DKK danish krone' },
  { code: '304', name: '德国马克', alias: 'DEM german mark' },
  { code: '305', name: '法国法郎', alias: 'FRF french franc' },
  { code: '309', name: '荷兰盾', alias: 'NLG dutch guilder' },
  { code: '326', name: '挪威克朗', alias: 'NOK norwegian krone' },
  { code: '330', name: '瑞典克朗', alias: 'SEK swedish krona' },
  { code: '332', name: '芬兰马克', alias: 'FIM finnish markka' },
  { code: '398', name: '欧洲货币单位', alias: 'XEU ecu' },
  { code: '501', name: '加拿大元', alias: 'CAD canadian dollar jianadayuan' },
  { code: '601', name: '澳大利亚元', alias: 'AUD australian dollar' },
  { code: '609', name: '新西兰元', alias: 'NZD new zealand dollar' },
  { code: '701', name: '瑞士法郎(旧)', alias: 'CHF old' },
  { code: '702', name: '新加坡元', alias: 'SGD singapore dollar xinjiapo yuan' },
  { code: '703', name: '泰国铢', alias: 'THB thai baht taizhu' },
  { code: '704', name: '菲律宾比索', alias: 'PHP philippine peso' },
  { code: '705', name: '缅甸元', alias: 'MMK burmese kyat' },
  { code: '706', name: '印度卢比', alias: 'INR indian rupee yindu lubi' },
  { code: '707', name: '巴基斯坦卢比', alias: 'PKR pakistan rupee' },
  { code: '708', name: '斯里兰卡卢比', alias: 'LKR sri lanka rupee' },
  { code: '800', name: '阿联酋迪拉姆', alias: 'AED dirham' },
  { code: '801', name: '韩国圆(旧)', alias: 'KRW old' },
  { code: '802', name: '越南盾', alias: 'VND dong' },
  { code: '803', name: '蒙古图格里克', alias: 'MNT tugrik' },
  { code: '806', name: '印度尼西亚卢比', alias: 'IDR rupiah' },
  { code: '810', name: '俄罗斯卢布', alias: 'RUB russian ruble eluosi lubu' },
  { code: '811', name: '白俄罗斯卢布', alias: 'BYN belarusian ruble' },
  { code: '817', name: '乌克兰格里夫纳', alias: 'UAH hryvnia' },
  { code: '818', name: '哈萨克斯坦坚戈', alias: 'KZT tenge' },
  { code: '819', name: '乌兹别克斯坦苏姆', alias: 'UZS som' },
  { code: '820', name: '吉尔吉斯斯坦索姆', alias: 'KGS som' },
  { code: '821', name: '塔吉克斯坦索莫尼', alias: 'TJS somoni' },
  { code: '822', name: '土库曼斯坦马纳特', alias: 'TMT manat' },
  { code: '826', name: '阿塞拜疆马纳特', alias: 'AZN manat' },
  { code: '827', name: '格鲁吉亚拉里', alias: 'GEL lari' },
  { code: '828', name: '亚美尼亚德拉姆', alias: 'AMD dram' },
  { code: '830', name: '墨西哥比索', alias: 'MXN mexican peso' },
  { code: '840', name: '巴西雷亚尔', alias: 'BRL brazilian real' },
  { code: '850', name: '智利比索', alias: 'CLP chilean peso' },
  { code: '852', name: '阿根廷比索', alias: 'ARS argentine peso' },
  { code: '855', name: '秘鲁索尔', alias: 'PEN sol' },
  { code: '856', name: '哥伦比亚比索', alias: 'COP colombian peso' },
  { code: '860', name: '乌拉圭比索', alias: 'UYU uruguayan peso' },
  { code: '865', name: '委内瑞拉玻利瓦尔', alias: 'VEF bolivar' },
  { code: '870', name: '埃及镑', alias: 'EGP egyptian pound' },
  { code: '880', name: '南非兰特', alias: 'ZAR south african rand' },
  { code: '886', name: '尼日利亚奈拉', alias: 'NGN naira' },
  { code: '890', name: '肯尼亚先令', alias: 'KES kenyan shilling' },
  { code: '899', name: '孟加拉国塔卡', alias: 'BDT taka' },
  { code: '900', name: '土耳其里拉', alias: 'TRY turkish lira' },
  { code: '901', name: '伊朗里亚尔', alias: 'IRR iranian rial' },
  { code: '902', name: '伊拉克第纳尔', alias: 'IQD iraqi dinar' },
  { code: '903', name: '沙特里亚尔', alias: 'SAR saudi riyal' },
  { code: '904', name: '科威特第纳尔', alias: 'KWD kuwaiti dinar' },
  { code: '905', name: '巴林第纳尔', alias: 'BHD bahraini dinar' },
  { code: '906', name: '卡塔尔里亚尔', alias: 'QAR qatari riyal' },
  { code: '907', name: '阿曼里亚尔', alias: 'OMR omani rial' },
  { code: '908', name: '约旦第纳尔', alias: 'JOD jordanian dinar' },
  { code: '909', name: '以色列谢克尔', alias: 'ILS israeli shekel' },
  { code: '910', name: '黎巴嫩镑', alias: 'LBP lebanese pound' },
  { code: '911', name: '叙利亚镑', alias: 'SYP syrian pound' },
  { code: '912', name: '也门里亚尔', alias: 'YER yemeni rial' },
  { code: '915', name: '马来西亚林吉特', alias: 'MYR malaysian ringgit' },
  { code: '920', name: '文莱元', alias: 'BND brunei dollar' },
  { code: '925', name: '印度尼西亚卢比(旧)', alias: 'IDR old' },
  { code: '932', name: '澳门元(旧)', alias: 'MOP old' },
  { code: '940', name: '柬埔寨瑞尔', alias: 'KHR riel' },
  { code: '945', name: '老挝基普', alias: 'LAK kip' },
  { code: '950', name: '不丹努尔特鲁姆', alias: 'BTN ngultrum' },
  { code: '955', name: '尼泊尔卢比', alias: 'NPR nepalese rupee' },
  { code: '960', name: '阿富汗尼', alias: 'AFN afghani' },
  { code: '970', name: '斐济元', alias: 'FJD fiji dollar' },
  { code: '975', name: '巴布亚新几内亚基那', alias: 'PGK kina' },
  { code: '980', name: '汤加潘加', alias: 'TOP paanga' },
  { code: '985', name: '萨摩亚塔拉', alias: 'WST tala' },
  { code: '990', name: '冰岛克朗', alias: 'ISK icelandic krona' },
  { code: '995', name: '阿尔巴尼亚列克', alias: 'ALL albanian lek' },
];

/** 通过 ISO 字母码（CNY/USD）反查数字 code */
export function findCurrencyByIso(iso: string): CustomsCodeItem | undefined {
  const map: Record<string, string> = {
    CNY: '142', USD: '502', EUR: '300', GBP: '303', JPY: '116', KRW: '133',
    HKD: '110', MOP: '121', TWD: '143', CHF: '331', DKK: '302', NOK: '326',
    SEK: '330', CAD: '501', AUD: '601', NZD: '609', SGD: '702', THB: '703',
    PHP: '704', INR: '706', RUB: '810', AED: '800', VND: '802', MNT: '803',
    IDR: '806', MXN: '830', BRL: '840', CLP: '850', ARS: '852', PEN: '855',
    COP: '856', EGP: '870', ZAR: '880', TRY: '900', SAR: '903', MYR: '915',
  };
  const code = map[iso.toUpperCase()];
  return code ? CURRENCIES.find((c) => c.code === code) : undefined;
}
