import type { CustomsCodeItem } from './types';

/**
 * 海关关别代码（4位）- 二手车出口重点口岸
 * 数据来源：海关总署关区代码表
 */
export const CUSTOMS_OFFICES: CustomsCodeItem[] = [
  // 广东（二手车出口量最大）
  { code: '5100', name: '广州海关', alias: 'guangzhou haiguan' },
  { code: '5101', name: '广州新风', alias: 'guangzhou xinfeng' },
  { code: '5102', name: '广州白云机场', alias: 'guangzhou baiyun' },
  { code: '5105', name: '广州黄埔', alias: 'guangzhou huangpu' },
  { code: '5130', name: '广州车站', alias: 'guangzhou chezhan' },
  { code: '5141', name: '广州黄埔老港', alias: 'huangpu laogang' },
  { code: '5142', name: '广州黄埔新港', alias: 'huangpu xingang' },
  { code: '5145', name: '广州番禺', alias: 'guangzhou panyu' },
  { code: '5149', name: '广州花都', alias: 'guangzhou huadu' },
  { code: '5150', name: '广州增城', alias: 'guangzhou zengcheng' },
  { code: '5165', name: '广州南沙湾', alias: 'nansha wan' },
  { code: '5166', name: '南沙新港', alias: 'nansha xingang' },
  { code: '5167', name: '广州南沙保税', alias: 'nansha baoshui' },
  { code: '5170', name: '广州会展中心', alias: 'huizhan' },
  { code: '5300', name: '深圳海关', alias: 'shenzhen haiguan' },
  { code: '5301', name: '深圳皇岗', alias: 'shenzhen huanggang' },
  { code: '5303', name: '深圳罗湖', alias: 'shenzhen luohu' },
  { code: '5304', name: '深圳蛇口', alias: 'shenzhen shekou' },
  { code: '5306', name: '深圳沙头角', alias: 'shenzhen shatoujiao' },
  { code: '5311', name: '深圳盐田港', alias: 'yantian gang' },
  { code: '5320', name: '深圳宝安机场', alias: 'shenzhen baoan' },
  { code: '5340', name: '深圳大铲湾', alias: 'dachanwan' },
  { code: '5349', name: '深圳前海湾', alias: 'qianhaiwan' },
  { code: '5700', name: '拱北海关', alias: 'gongbei zhuhai' },
  { code: '5710', name: '珠海横琴', alias: 'zhuhai hengqin' },
  { code: '5720', name: '珠海九洲', alias: 'zhuhai jiuzhou' },
  { code: '5730', name: '珠海湾仔', alias: 'zhuhai wanzai' },
  { code: '5790', name: '港珠澳大桥', alias: 'gangzhuao daqiao' },
  { code: '6000', name: '汕头海关', alias: 'shantou haiguan' },
  { code: '6003', name: '汕头港', alias: 'shantou gang' },
  { code: '6010', name: '汕头潮阳', alias: 'shantou chaoyang' },
  { code: '5200', name: '黄埔海关', alias: 'huangpu haiguan' },
  { code: '5210', name: '东莞海关', alias: 'dongguan haiguan' },
  { code: '5220', name: '太平海关', alias: 'taiping' },
  { code: '5230', name: '常平海关', alias: 'changping' },
  { code: '5240', name: '凤岗海关', alias: 'fenggang' },
  { code: '5250', name: '长安海关', alias: 'changan' },
  { code: '5700', name: '湛江海关', alias: 'zhanjiang haiguan' },
  { code: '5710', name: '湛江港', alias: 'zhanjiang gang' },
  { code: '7100', name: '江门海关', alias: 'jiangmen haiguan' },
  { code: '7110', name: '新会海关', alias: 'xinhui' },
  { code: '7120', name: '台山海关', alias: 'taishan' },
  { code: '7130', name: '开平海关', alias: 'kaiping' },
  { code: '7140', name: '鹤山海关', alias: 'heshan' },
  { code: '7150', name: '恩平海关', alias: 'enping' },
  { code: '5760', name: '茂名海关', alias: 'maoming' },
  // 上海
  { code: '2200', name: '上海海关', alias: 'shanghai haiguan' },
  { code: '2201', name: '上海浦江', alias: 'shanghai pujiang' },
  { code: '2202', name: '上海吴淞', alias: 'shanghai wusong' },
  { code: '2203', name: '上海机场', alias: 'shanghai jichang' },
  { code: '2204', name: '上海邮局', alias: 'shanghai youju' },
  { code: '2210', name: '上海外高桥港区', alias: 'waigaoqiao gangqu' },
  { code: '2218', name: '上海外高桥保税区', alias: 'waigaoqiao baoshuiqu' },
  { code: '2225', name: '上海洋山港区', alias: 'yangshan gangqu' },
  { code: '2226', name: '上海洋山保税港区', alias: 'yangshan baoshui' },
  { code: '2230', name: '上海浦东机场', alias: 'pudong jichang' },
  { code: '2233', name: '上海浦东海关', alias: 'pudong haiguan' },
  { code: '2244', name: '上海会展中心', alias: 'shanghai huizhan' },
  { code: '2248', name: '上海洋山', alias: 'shanghai yangshan' },
  { code: '2249', name: '上海洋山海关', alias: 'yangshan haiguan' },
  // 天津
  { code: '0200', name: '天津海关', alias: 'tianjin haiguan' },
  { code: '0201', name: '天津新港', alias: 'tianjin xingang' },
  { code: '0202', name: '天津新港海关', alias: 'tianjin xingang haiguan' },
  { code: '0203', name: '天津东港', alias: 'tianjin donggang' },
  { code: '0204', name: '天津东港海关', alias: 'tianjin donggang haiguan' },
  { code: '0205', name: '天津机场', alias: 'tianjin jichang' },
  { code: '0207', name: '天津保税区', alias: 'tianjin baoshuiqu' },
  { code: '0210', name: '天津东疆保税港区', alias: 'dongjiang baoshui' },
  { code: '0212', name: '天津蓟州', alias: 'tianjin jizhou' },
  // 辽宁
  { code: '0900', name: '大连海关', alias: 'dalian haiguan' },
  { code: '0901', name: '大连港湾', alias: 'dalian gangwan' },
  { code: '0902', name: '大连大窑湾', alias: 'dalian dayaowan' },
  { code: '0903', name: '大连机场', alias: 'dalian jichang' },
  { code: '0908', name: '大连保税区', alias: 'dalian baoshuiqu' },
  { code: '0910', name: '大连长兴岛', alias: 'dalian changxingdao' },
  { code: '0800', name: '沈阳海关', alias: 'shenyang haiguan' },
  { code: '0801', name: '沈阳机场', alias: 'shenyang jichang' },
  { code: '1500', name: '营口海关', alias: 'yingkou' },
  // 山东
  { code: '4200', name: '青岛海关', alias: 'qingdao haiguan' },
  { code: '4201', name: '青岛大港', alias: 'qingdao dagang' },
  { code: '4202', name: '青岛前湾', alias: 'qingdao qianwan' },
  { code: '4204', name: '青岛机场', alias: 'qingdao jichang' },
  { code: '4210', name: '青岛保税区', alias: 'qingdao baoshuiqu' },
  { code: '4211', name: '青岛董家口', alias: 'qingdao dongjiakou' },
  { code: '4218', name: '青岛黄岛', alias: 'qingdao huangdao' },
  { code: '4220', name: '烟台海关', alias: 'yantai haiguan' },
  { code: '4221', name: '烟台港', alias: 'yantai gang' },
  { code: '4230', name: '威海海关', alias: 'weihai haiguan' },
  { code: '4231', name: '威海港', alias: 'weihai gang' },
  { code: '4240', name: '日照海关', alias: 'rizhao haiguan' },
  { code: '4250', name: '潍坊海关', alias: 'weifang haiguan' },
  { code: '4260', name: '济南海关', alias: 'jinan haiguan' },
  { code: '4270', name: '临沂海关', alias: 'linyi haiguan' },
  // 浙江
  { code: '3100', name: '杭州海关', alias: 'hangzhou haiguan' },
  { code: '3101', name: '杭州机场', alias: 'hangzhou jichang' },
  { code: '3104', name: '杭州快件', alias: 'hangzhou kuaijian' },
  { code: '3110', name: '宁波海关', alias: 'ningbo haiguan' },
  { code: '3111', name: '宁波北仑', alias: 'ningbo beilun' },
  { code: '3112', name: '宁波镇海', alias: 'ningbo zhenhai' },
  { code: '3114', name: '宁波保税区', alias: 'ningbo baoshuiqu' },
  { code: '3118', name: '宁波大榭', alias: 'ningbo daxie' },
  { code: '3119', name: '宁波梅山', alias: 'ningbo meishan' },
  { code: '3120', name: '宁波机场', alias: 'ningbo jichang' },
  { code: '3140', name: '温州海关', alias: 'wenzhou haiguan' },
  { code: '3141', name: '温州机场', alias: 'wenzhou jichang' },
  { code: '3150', name: '舟山海关', alias: 'zhoushan haiguan' },
  { code: '3151', name: '舟山甬兴', alias: 'zhoushan yongxing' },
  { code: '3160', name: '台州海关', alias: 'taizhou haiguan' },
  { code: '3170', name: '嘉兴海关', alias: 'jiaxing haiguan' },
  { code: '3180', name: '绍兴海关', alias: 'shaoxing haiguan' },
  { code: '3190', name: '湖州海关', alias: 'huzhou haiguan' },
  { code: '3191', name: '金华海关', alias: 'jinhua haiguan' },
  { code: '3192', name: '义乌海关', alias: 'yiwu haiguan' },
  // 江苏
  { code: '2300', name: '南京海关', alias: 'nanjing haiguan' },
  { code: '2301', name: '南京机场', alias: 'nanjing jichang' },
  { code: '2310', name: '苏州海关', alias: 'suzhou haiguan' },
  { code: '2311', name: '苏州工业园区', alias: 'suzhou gongyeyuanqu' },
  { code: '2312', name: '苏州高新技术产业开发区', alias: 'suzhou gaoqu' },
  { code: '2313', name: '苏州太仓', alias: 'suzhou taicang' },
  { code: '2314', name: '苏州张家港', alias: 'suzhou zhangjiagang' },
  { code: '2320', name: '无锡海关', alias: 'wuxi haiguan' },
  { code: '2321', name: '无锡机场', alias: 'wuxi jichang' },
  { code: '2330', name: '常州海关', alias: 'changzhou haiguan' },
  { code: '2340', name: '南通海关', alias: 'nantong haiguan' },
  { code: '2341', name: '南通启东', alias: 'nantong qidong' },
  { code: '2350', name: '连云港海关', alias: 'lianyungang haiguan' },
  { code: '2360', name: '徐州海关', alias: 'xuzhou haiguan' },
  { code: '2370', name: '扬州海关', alias: 'yangzhou haiguan' },
  { code: '2380', name: '镇江海关', alias: 'zhenjiang haiguan' },
  { code: '2390', name: '盐城海关', alias: 'yancheng haiguan' },
  { code: '2391', name: '泰州海关', alias: 'taizhou haiguan' },
  { code: '2392', name: '淮安海关', alias: 'huaian haiguan' },
  // 福建
  { code: '3500', name: '福州海关', alias: 'fuzhou haiguan' },
  { code: '3501', name: '福州马尾', alias: 'fuzhou mawei' },
  { code: '3502', name: '福州机场', alias: 'fuzhou jichang' },
  { code: '3510', name: '厦门海关', alias: 'xiamen haiguan' },
  { code: '3511', name: '厦门东渡', alias: 'xiamen dongdu' },
  { code: '3512', name: '厦门高崎机场', alias: 'xiamen gaoqi' },
  { code: '3513', name: '厦门海沧', alias: 'xiamen haicang' },
  { code: '3514', name: '厦门象屿', alias: 'xiamen xiangyu' },
  { code: '3520', name: '泉州海关', alias: 'quanzhou haiguan' },
  { code: '3521', name: '泉州晋江', alias: 'quanzhou jinjiang' },
  { code: '3530', name: '漳州海关', alias: 'zhangzhou haiguan' },
  { code: '3540', name: '莆田海关', alias: 'putian haiguan' },
  { code: '3550', name: '三明海关', alias: 'sanming haiguan' },
  { code: '3560', name: '南平海关', alias: 'nanping haiguan' },
  { code: '3570', name: '龙岩海关', alias: 'longyan haiguan' },
  { code: '3580', name: '宁德海关', alias: 'ningde haiguan' },
  // 湖北
  { code: '4700', name: '武汉海关', alias: 'wuhan haiguan' },
  { code: '4701', name: '武汉机场', alias: 'wuhan jichang' },
  { code: '4702', name: '武汉新港', alias: 'wuhan xingang' },
  { code: '4710', name: '武汉东湖综合保税区', alias: 'wuhan donghu' },
  { code: '4720', name: '宜昌海关', alias: 'yichang haiguan' },
  { code: '4730', name: '黄石海关', alias: 'huangshi haiguan' },
  // 四川、重庆
  { code: '8000', name: '重庆海关', alias: 'chongqing haiguan' },
  { code: '8001', name: '重庆江北机场', alias: 'chongqing jiangbei' },
  { code: '8002', name: '重庆寸滩', alias: 'chongqing cuntan' },
  { code: '8003', name: '重庆两路', alias: 'chongqing lianglu' },
  { code: '8010', name: '重庆西永', alias: 'chongqing xiyong' },
  { code: '8600', name: '成都海关', alias: 'chengdu haiguan' },
  { code: '8601', name: '成都双流机场', alias: 'chengdu shuangliu' },
  { code: '8602', name: '成都天府机场', alias: 'chengdu tianfu' },
  { code: '8610', name: '成都高新综合保税区', alias: 'chengdu gaoxin' },
  { code: '8620', name: '绵阳海关', alias: 'mianyang haiguan' },
  // 其他
  { code: '4900', name: '长沙海关', alias: 'changsha haiguan' },
  { code: '4901', name: '长沙黄花机场', alias: 'changsha huanghua' },
  { code: '4000', name: '南昌海关', alias: 'nanchang haiguan' },
  { code: '4600', name: '郑州海关', alias: 'zhengzhou haiguan' },
  { code: '4601', name: '郑州机场', alias: 'zhengzhou jichang' },
  { code: '3000', name: '合肥海关', alias: 'hefei haiguan' },
  { code: '3010', name: '合肥机场', alias: 'hefei jichang' },
  { code: '3400', name: '西安海关', alias: 'xian haiguan' },
  { code: '3401', name: '西安机场', alias: 'xian jichang' },
  { code: '6800', name: '昆明海关', alias: 'kunming haiguan' },
  { code: '6900', name: '南宁海关', alias: 'nanning haiguan' },
  { code: '6910', name: '钦州保税港区', alias: 'qinzhou baoshui' },
  { code: '6920', name: '凭祥海关', alias: 'pingxiang' },
  { code: '6930', name: '东兴海关', alias: 'dongxing' },
  { code: '7200', name: '海口海关', alias: 'haikou haiguan' },
  { code: '7210', name: '海口港', alias: 'haikou gang' },
  { code: '7220', name: '三亚海关', alias: 'sanya haiguan' },
  { code: '7230', name: '洋浦经济开发区', alias: 'yangpu jingkaiqu' },
  { code: '6400', name: '贵阳海关', alias: 'guiyang haiguan' },
  { code: '1900', name: '哈尔滨海关', alias: 'haerbin haiguan' },
  { code: '1910', name: '绥芬河海关', alias: 'suifenhe' },
  { code: '1920', name: '黑河海关', alias: 'heihe' },
  { code: '1500', name: '长春海关', alias: 'changchun haiguan' },
  { code: '1510', name: '珲春海关', alias: 'huichun' },
  { code: '7000', name: '兰州海关', alias: 'lanzhou haiguan' },
  { code: '8300', name: '贵阳海关', alias: 'guiyang' },
  // 公路口岸（对港/对俄/对中亚）
  { code: '5301', name: '皇岗海关', alias: 'huanggang gonglukouan' },
  { code: '5307', name: '深圳文锦渡', alias: 'wenjindu' },
  { code: '5308', name: '深圳沙头角', alias: 'shatoujiao gonglu' },
  { code: '5345', name: '深圳深圳湾', alias: 'shenzhenwan' },
  { code: '0500', name: '二连海关', alias: 'erlian menggu' },
  { code: '0600', name: '满洲里海关', alias: 'manzhouli' },
  { code: '9400', name: '阿拉山口海关', alias: 'alashankou hasakesitan' },
  { code: '9410', name: '霍尔果斯海关', alias: 'huoerguosi' },
  { code: '9500', name: '吐尔尕特海关', alias: 'tuergaate jierjisi' },
  { code: '9510', name: '伊尔克什坦海关', alias: 'yierkeshentan' },
  { code: '6920', name: '友谊关海关', alias: 'youyiguan yuenan' },
  { code: '6930', name: '东兴口岸', alias: 'dongxing yuenan' },
  { code: '6940', name: '水口海关', alias: 'shuikou yuenan' },
  { code: '6950', name: '龙邦海关', alias: 'longbang yuenan' },
];
