import type { CustomsCodeItem } from './types';

/**
 * 境内货源地代码（5位）- 二手车出口常用子集
 *
 * 数据来源：海关总署《关区代码》《国内地区代码表》。
 * 仅收录业务高频地区，其他地区用户可通过"代码表维护"功能自行补充。
 * 编码规则：前2位=省/直辖市代码，后3位=区县/特殊监管区。
 */
export const DOMESTIC_SOURCES: CustomsCodeItem[] = [
  // 北京
  { code: '11013', name: '中关村国家自主创新示范区(东城园)', alias: 'beijing dongcheng zgc' },
  { code: '11019', name: '东城区', alias: 'beijing dongcheng' },
  { code: '11023', name: '中关村国家自主创新示范区(西城园)', alias: 'beijing xicheng zgc' },
  { code: '11029', name: '西城区', alias: 'beijing xicheng' },
  { code: '11039', name: '崇文区', alias: 'beijing chongwen' },
  { code: '11049', name: '宣武区', alias: 'beijing xuanwu' },
  { code: '11053', name: '中关村国家自主创新示范区(朝阳园)', alias: 'beijing chaoyang zgc' },
  { code: '11059', name: '朝阳区', alias: 'beijing chaoyang' },
  { code: '11063', name: '中关村国家自主创新示范区(丰台园)', alias: 'beijing fengtai zgc' },
  { code: '11069', name: '丰台区', alias: 'beijing fengtai' },
  { code: '11113', name: '北京经济技术开发区', alias: 'beijing yizhuang jingkaiqu' },
  { code: '11119', name: '大兴区', alias: 'beijing daxing' },
  { code: '11139', name: '顺义区', alias: 'beijing shunyi' },
  // 上海
  { code: '31019', name: '黄浦区', alias: 'shanghai huangpu' },
  { code: '31049', name: '徐汇区', alias: 'shanghai xuhui' },
  { code: '31059', name: '长宁区', alias: 'shanghai changning' },
  { code: '31079', name: '普陀区', alias: 'shanghai putuo' },
  { code: '31099', name: '静安区', alias: 'shanghai jingan' },
  { code: '31109', name: '闸北区', alias: 'shanghai zhabei' },
  { code: '31119', name: '虹口区', alias: 'shanghai hongkou' },
  { code: '31129', name: '杨浦区', alias: 'shanghai yangpu' },
  { code: '31159', name: '闵行区', alias: 'shanghai minhang' },
  { code: '31169', name: '宝山区', alias: 'shanghai baoshan' },
  { code: '31179', name: '嘉定区', alias: 'shanghai jiading' },
  { code: '31189', name: '浦东新区', alias: 'shanghai pudong' },
  { code: '31222', name: '上海浦东新区', alias: 'shanghai pudongxinqu gaqiao' },
  { code: '31199', name: '金山区', alias: 'shanghai jinshan' },
  { code: '31209', name: '松江区', alias: 'shanghai songjiang' },
  { code: '31219', name: '青浦区', alias: 'shanghai qingpu' },
  { code: '31229', name: '奉贤区', alias: 'shanghai fengxian' },
  { code: '31909', name: '上海外高桥保税区', alias: 'shanghai waigaoqiao baoeshuiqu' },
  { code: '31909', name: '洋山保税港区', alias: 'shanghai yangshan' },
  // 广东（二手车出口重点）
  { code: '44012', name: '广州经济技术开发区', alias: 'guangzhou jingkaiqu' },
  { code: '44019', name: '广州越秀区', alias: 'guangzhou yuexiu' },
  { code: '44029', name: '广州海珠区', alias: 'guangzhou haizhu' },
  { code: '44039', name: '广州荔湾区', alias: 'guangzhou liwan' },
  { code: '44049', name: '广州天河区', alias: 'guangzhou tianhe' },
  { code: '44059', name: '广州白云区', alias: 'guangzhou baiyun' },
  { code: '44069', name: '广州黄埔区', alias: 'guangzhou huangpu' },
  { code: '44079', name: '广州番禺区', alias: 'guangzhou panyu' },
  { code: '44089', name: '广州花都区', alias: 'guangzhou huadu' },
  { code: '44099', name: '广州南沙区', alias: 'guangzhou nansha' },
  { code: '44109', name: '广州从化区', alias: 'guangzhou conghua' },
  { code: '44119', name: '广州增城区', alias: 'guangzhou zengcheng' },
  { code: '44209', name: '深圳罗湖区', alias: 'shenzhen luohu' },
  { code: '44219', name: '深圳福田区', alias: 'shenzhen futian' },
  { code: '44229', name: '深圳南山区', alias: 'shenzhen nanshan' },
  { code: '44239', name: '深圳宝安区', alias: 'shenzhen baoan' },
  { code: '44249', name: '深圳龙岗区', alias: 'shenzhen longgang' },
  { code: '44259', name: '深圳盐田区', alias: 'shenzhen yantian' },
  { code: '44269', name: '深圳龙华区', alias: 'shenzhen longhua' },
  { code: '44279', name: '深圳坪山区', alias: 'shenzhen pingshan' },
  { code: '44289', name: '深圳光明区', alias: 'shenzhen guangming' },
  { code: '44409', name: '珠海香洲区', alias: 'zhuhai xiangzhou' },
  { code: '44419', name: '汕头金平区', alias: 'shantou jinping' },
  { code: '44509', name: '佛山禅城区', alias: 'foshan chancheng' },
  { code: '44519', name: '佛山南海区', alias: 'foshan nanhai' },
  { code: '44529', name: '佛山顺德区', alias: 'foshan shunde' },
  { code: '44539', name: '佛山三水区', alias: 'foshan sanshui' },
  { code: '44549', name: '佛山高明区', alias: 'foshan gaoming' },
  { code: '44609', name: '韶关武江区', alias: 'shaoguan wujiang' },
  { code: '44709', name: '湛江赤坎区', alias: 'zhanjiang chikan' },
  { code: '44719', name: '湛江霞山区', alias: 'zhanjiang xiashan' },
  { code: '44809', name: '肇庆端州区', alias: 'zhaoqing duanzhou' },
  { code: '44909', name: '江门蓬江区', alias: 'jiangmen pengjiang' },
  { code: '44919', name: '东莞', alias: 'dongguan' },
  { code: '44929', name: '中山', alias: 'zhongshan' },
  { code: '44939', name: '惠州惠城区', alias: 'huizhou huicheng' },
  // 天津
  { code: '12019', name: '天津和平区', alias: 'tianjin heping' },
  { code: '12049', name: '天津河西区', alias: 'tianjin hexi' },
  { code: '12079', name: '天津南开区', alias: 'tianjin nankai' },
  { code: '12109', name: '天津塘沽区', alias: 'tianjin tanggu' },
  { code: '12119', name: '天津汉沽区', alias: 'tianjin hangu' },
  { code: '12129', name: '天津大港区', alias: 'tianjin dagang' },
  { code: '12139', name: '天津东丽区', alias: 'tianjin dongli' },
  { code: '12149', name: '天津西青区', alias: 'tianjin xiqing' },
  { code: '12159', name: '天津津南区', alias: 'tianjin jinnan' },
  { code: '12169', name: '天津北辰区', alias: 'tianjin beichen' },
  { code: '12909', name: '天津港保税区', alias: 'tianjin gang baoshuiqu' },
  // 重庆
  { code: '50019', name: '重庆渝中区', alias: 'chongqing yuzhong' },
  { code: '50049', name: '重庆江北区', alias: 'chongqing jiangbei' },
  { code: '50059', name: '重庆沙坪坝区', alias: 'chongqing shapingba' },
  { code: '50069', name: '重庆九龙坡区', alias: 'chongqing jiulongpo' },
  { code: '50079', name: '重庆南岸区', alias: 'chongqing nanan' },
  { code: '50089', name: '重庆北碚区', alias: 'chongqing beibei' },
  { code: '50109', name: '重庆渝北区', alias: 'chongqing yubei' },
  { code: '50119', name: '重庆巴南区', alias: 'chongqing banan' },
  { code: '50909', name: '重庆两路寸滩保税港区', alias: 'chongqing cuntan' },
  // 浙江
  { code: '33019', name: '杭州上城区', alias: 'hangzhou shangcheng' },
  { code: '33029', name: '杭州下城区', alias: 'hangzhou xiacheng' },
  { code: '33039', name: '杭州江干区', alias: 'hangzhou jianggan' },
  { code: '33049', name: '杭州拱墅区', alias: 'hangzhou gongshu' },
  { code: '33059', name: '杭州西湖区', alias: 'hangzhou xihu' },
  { code: '33069', name: '杭州滨江区', alias: 'hangzhou binjiang' },
  { code: '33079', name: '杭州萧山区', alias: 'hangzhou xiaoshan' },
  { code: '33089', name: '杭州余杭区', alias: 'hangzhou yuhang' },
  { code: '33129', name: '宁波海曙区', alias: 'ningbo haishu' },
  { code: '33139', name: '宁波江北区', alias: 'ningbo jiangbei' },
  { code: '33149', name: '宁波北仑区', alias: 'ningbo beilun' },
  { code: '33159', name: '宁波镇海区', alias: 'ningbo zhenhai' },
  { code: '33169', name: '宁波鄞州区', alias: 'ningbo yinzhou' },
  { code: '33909', name: '宁波保税区', alias: 'ningbo baoshuiqu' },
  { code: '33209', name: '温州鹿城区', alias: 'wenzhou lucheng' },
  { code: '33309', name: '嘉兴南湖区', alias: 'jiaxing nanhu' },
  { code: '33409', name: '湖州吴兴区', alias: 'huzhou wuxing' },
  { code: '33509', name: '绍兴越城区', alias: 'shaoxing yuecheng' },
  { code: '33609', name: '金华婺城区', alias: 'jinhua wucheng' },
  { code: '33709', name: '衢州柯城区', alias: 'quzhou kecheng' },
  { code: '33809', name: '舟山定海区', alias: 'zhoushan dinghai' },
  { code: '33919', name: '台州椒江区', alias: 'taizhou jiaojiang' },
  { code: '33929', name: '丽水莲都区', alias: 'lishui liandu' },
  // 江苏
  { code: '32019', name: '南京玄武区', alias: 'nanjing xuanwu' },
  { code: '32029', name: '南京白下区', alias: 'nanjing baixia' },
  { code: '32039', name: '南京秦淮区', alias: 'nanjing qinhuai' },
  { code: '32049', name: '南京建邺区', alias: 'nanjing jianye' },
  { code: '32059', name: '南京鼓楼区', alias: 'nanjing gulou' },
  { code: '32069', name: '南京下关区', alias: 'nanjing xiaguan' },
  { code: '32079', name: '南京浦口区', alias: 'nanjing pukou' },
  { code: '32089', name: '南京栖霞区', alias: 'nanjing qixia' },
  { code: '32099', name: '南京雨花台区', alias: 'nanjing yuhuatai' },
  { code: '32109', name: '南京江宁区', alias: 'nanjing jiangning' },
  { code: '32159', name: '苏州姑苏区', alias: 'suzhou gusu' },
  { code: '32169', name: '苏州虎丘区', alias: 'suzhou huqiu' },
  { code: '32179', name: '苏州吴中区', alias: 'suzhou wuzhong' },
  { code: '32189', name: '苏州相城区', alias: 'suzhou xiangcheng' },
  { code: '32199', name: '苏州吴江区', alias: 'suzhou wujiang' },
  { code: '32209', name: '苏州工业园区', alias: 'suzhou gongyeyuanqu sip' },
  { code: '32259', name: '常州天宁区', alias: 'changzhou tianning' },
  { code: '32269', name: '常州钟楼区', alias: 'changzhou zhonglou' },
  { code: '32279', name: '常州新北区', alias: 'changzhou xinbei' },
  { code: '32289', name: '常州武进区', alias: 'changzhou wujin' },
  { code: '32909', name: '苏州高新技术产业开发区', alias: 'suzhou gaoqu' },
  { code: '32309', name: '无锡崇安区', alias: 'wuxi chongan' },
  { code: '32319', name: '无锡南长区', alias: 'wuxi nanchang' },
  { code: '32329', name: '无锡北塘区', alias: 'wuxi beitang' },
  { code: '32339', name: '无锡锡山区', alias: 'wuxi xishan' },
  { code: '32349', name: '无锡惠山区', alias: 'wuxi huishan' },
  { code: '32359', name: '无锡滨江区', alias: 'wuxi binjiang' },
  { code: '32409', name: '南通崇川区', alias: 'nantong chongchuan' },
  { code: '32419', name: '南通港闸区', alias: 'nantong gangzha' },
  { code: '32509', name: '连云港连云区', alias: 'lianyungang lianyun' },
  { code: '32609', name: '淮安清河区', alias: 'huaian qinghe' },
  { code: '32709', name: '盐城亭湖区', alias: 'yancheng tinghu' },
  { code: '32809', name: '扬州广陵区', alias: 'yangzhou guangling' },
  { code: '32909', name: '镇江京口区', alias: 'zhenjiang jingkou' },
  { code: '32919', name: '泰州海陵区', alias: 'taizhou hailing' },
  { code: '32929', name: '宿迁宿城区', alias: 'suqian suc' },
  // 山东
  { code: '37019', name: '济南历下区', alias: 'jinan lixia' },
  { code: '37029', name: '济南市中区', alias: 'jinan shizhong' },
  { code: '37039', name: '济南槐荫区', alias: 'jinan huaiyin' },
  { code: '37049', name: '济南天桥区', alias: 'jinan tianqiao' },
  { code: '37059', name: '济南历城区', alias: 'jinan licheng' },
  { code: '37069', name: '济南长清区', alias: 'jinan changqing' },
  { code: '37109', name: '青岛市南区', alias: 'qingdao shinan' },
  { code: '37119', name: '青岛市北区', alias: 'qingdao shibei' },
  { code: '37129', name: '青岛四方区', alias: 'qingdao sifang' },
  { code: '37139', name: '青岛黄岛区', alias: 'qingdao huangdao' },
  { code: '37149', name: '青岛崂山区', alias: 'qingdao laoshan' },
  { code: '37159', name: '青岛李沧区', alias: 'qingdao licang' },
  { code: '37169', name: '青岛城阳区', alias: 'qingdao chengyang' },
  { code: '37909', name: '青岛保税区', alias: 'qingdao baoshuiqu' },
  { code: '37209', name: '淄博张店区', alias: 'zibo zhangdian' },
  { code: '37309', name: '枣庄市中区', alias: 'zaozhuang shizhong' },
  { code: '37409', name: '东营东营区', alias: 'dongying dongyingqu' },
  { code: '37509', name: '烟台芝罘区', alias: 'yantai zhifu' },
  { code: '37919', name: '烟台保税区', alias: 'yantai baoshuiqu' },
  { code: '37609', name: '潍坊潍城区', alias: 'weifang weicheng' },
  { code: '37709', name: '济宁市中区', alias: 'jining shizhong' },
  { code: '37809', name: '泰安泰山区', alias: 'taian taishan' },
  { code: '37929', name: '威海环翠区', alias: 'weihai huancui' },
  { code: '37939', name: '日照东港区', alias: 'rizhao donggang' },
  // 四川
  { code: '51019', name: '成都锦江区', alias: 'chengdu jinjiang' },
  { code: '51029', name: '成都青羊区', alias: 'chengdu qingyang' },
  { code: '51039', name: '成都金牛区', alias: 'chengdu jinniu' },
  { code: '51049', name: '成都武侯区', alias: 'chengdu wuhou' },
  { code: '51059', name: '成都成华区', alias: 'chengdu chenghua' },
  { code: '51069', name: '成都龙泉驿区', alias: 'chengdu longquanyi' },
  { code: '51079', name: '成都青白江区', alias: 'chengdu qingbaijiang' },
  { code: '51089', name: '成都新都区', alias: 'chengdu xindu' },
  { code: '51099', name: '成都温江区', alias: 'chengdu wenjiang' },
  { code: '51109', name: '成都双流区', alias: 'chengdu shuangliu' },
  { code: '51119', name: '成都郫都区', alias: 'chengdu pidou' },
  { code: '51909', name: '成都高新综合保税区', alias: 'chengdu gaoxin baoshuiqu' },
  { code: '51209', name: '自贡自流井区', alias: 'zigong ziliujing' },
  { code: '51309', name: '攀枝花东区', alias: 'panzhihua dongqu' },
  { code: '51409', name: '泸州江阳区', alias: 'luzhou jiangyang' },
  { code: '51509', name: '德阳旌阳区', alias: 'deyang jingyang' },
  { code: '51609', name: '绵阳涪城区', alias: 'mianyang fucheng' },
  // 湖北（武汉）
  { code: '42019', name: '武汉江岸区', alias: 'wuhan jiangan' },
  { code: '42029', name: '武汉江汉区', alias: 'wuhan jianghan' },
  { code: '42039', name: '武汉硚口区', alias: 'wuhan qiaokou' },
  { code: '42049', name: '武汉汉阳区', alias: 'wuhan hanyang' },
  { code: '42059', name: '武汉武昌区', alias: 'wuhan wuchang' },
  { code: '42069', name: '武汉青山区', alias: 'wuhan qingshan' },
  { code: '42079', name: '武汉洪山区', alias: 'wuhan hongshan' },
  { code: '42089', name: '武汉东西湖区', alias: 'wuhan dongxihu' },
  { code: '42099', name: '武汉汉南区', alias: 'wuhan hannan' },
  { code: '42109', name: '武汉蔡甸区', alias: 'wuhan caidian' },
  { code: '42119', name: '武汉江夏区', alias: 'wuhan jiangxia' },
  { code: '42129', name: '武汉黄陂区', alias: 'wuhan huangpi' },
  { code: '42139', name: '武汉新洲区', alias: 'wuhan xinzhou' },
  // 福建
  { code: '35019', name: '福州鼓楼区', alias: 'fuzhou gulou' },
  { code: '35029', name: '福州台江区', alias: 'fuzhou taijiang' },
  { code: '35039', name: '福州仓山区', alias: 'fuzhou cangshan' },
  { code: '35049', name: '福州马尾区', alias: 'fuzhou mawei' },
  { code: '35059', name: '福州晋安区', alias: 'fuzhou jinan' },
  { code: '35109', name: '厦门思明区', alias: 'xiamen siming' },
  { code: '35119', name: '厦门海沧区', alias: 'xiamen haicang' },
  { code: '35129', name: '厦门湖里区', alias: 'xiamen huli' },
  { code: '35139', name: '厦门集美区', alias: 'xiamen jimei' },
  { code: '35149', name: '厦门同安区', alias: 'xiamen tongan' },
  { code: '35159', name: '厦门翔安区', alias: 'xiamen xiangan' },
  { code: '35909', name: '厦门象屿保税区', alias: 'xiamen xiangyu' },
  { code: '35209', name: '莆田城厢区', alias: 'putian chengxiang' },
  { code: '35309', name: '三明梅列区', alias: 'sanming meilie' },
  { code: '35409', name: '泉州鲤城区', alias: 'quanzhou licheng' },
  { code: '35419', name: '泉州丰泽区', alias: 'quanzhou fengze' },
  { code: '35509', name: '漳州芗城区', alias: 'zhangzhou xiangcheng' },
  // 河南
  { code: '41019', name: '郑州中原区', alias: 'zhengzhou zhongyuan' },
  { code: '41029', name: '郑州二七区', alias: 'zhengzhou erqi' },
  { code: '41039', name: '郑州管城回族区', alias: 'zhengzhou guancheng' },
  { code: '41049', name: '郑州金水区', alias: 'zhengzhou jinshui' },
  { code: '41059', name: '郑州上街区', alias: 'zhengzhou shangjie' },
  { code: '41069', name: '郑州惠济区', alias: 'zhengzhou huiji' },
  { code: '41079', name: '郑州中牟县', alias: 'zhengzhou zhongmou' },
  { code: '41089', name: '郑州巩义市', alias: 'zhengzhou gongyi' },
  { code: '41099', name: '郑州荥阳市', alias: 'zhengzhou xingyang' },
  { code: '41109', name: '郑州新密市', alias: 'zhengzhou xinmi' },
  { code: '41119', name: '郑州新郑市', alias: 'zhengzhou xinzheng' },
  { code: '41129', name: '郑州登封市', alias: 'zhengzhou dengfeng' },
  // 辽宁
  { code: '21019', name: '沈阳和平区', alias: 'shenyang heping' },
  { code: '21029', name: '沈阳沈河区', alias: 'shenyang shenhe' },
  { code: '21039', name: '沈阳大东区', alias: 'shenyang dadong' },
  { code: '21049', name: '沈阳皇姑区', alias: 'shenyang huanggu' },
  { code: '21059', name: '沈阳铁西区', alias: 'shenyang tiexi' },
  { code: '21109', name: '大连中山区', alias: 'dalian zhongshan' },
  { code: '21119', name: '大连西岗区', alias: 'dalian xigang' },
  { code: '21129', name: '大连沙河口区', alias: 'dalian shahekou' },
  { code: '21139', name: '大连甘井子区', alias: 'dalian ganjingzi' },
  { code: '21149', name: '大连旅顺口区', alias: 'dalian lvshunkou' },
  { code: '21159', name: '大连金州区', alias: 'dalian jinzhou' },
  { code: '21909', name: '大连保税区', alias: 'dalian baoshuiqu' },
  // 吉林、黑龙江
  { code: '22019', name: '长春南关区', alias: 'changchun nanguan' },
  { code: '23019', name: '哈尔滨道里区', alias: 'haerbin daoli' },
  // 陕西
  { code: '61019', name: '西安新城区', alias: 'xian xincheng' },
  { code: '61029', name: '西安碑林区', alias: 'xian beilin' },
  { code: '61039', name: '西安莲湖区', alias: 'xian lianhu' },
  { code: '61049', name: '西安灞桥区', alias: 'xian baqiao' },
  { code: '61059', name: '西安未央区', alias: 'xian weiyang' },
  { code: '61069', name: '西安雁塔区', alias: 'xian yanta' },
  { code: '61909', name: '西安综合保税区', alias: 'xian zonghebaoshui' },
  // 安徽
  { code: '34019', name: '合肥瑶海区', alias: 'hefei yaohai' },
  { code: '34029', name: '合肥庐阳区', alias: 'hefei luyang' },
  { code: '34039', name: '合肥蜀山区', alias: 'hefei shushan' },
  { code: '34049', name: '合肥包河区', alias: 'hefei baohe' },
  // 湖南
  { code: '43019', name: '长沙芙蓉区', alias: 'changsha furong' },
  { code: '43029', name: '长沙天心区', alias: 'changsha tianxin' },
  { code: '43039', name: '长沙岳麓区', alias: 'changsha yuelu' },
  { code: '43049', name: '长沙开福区', alias: 'changsha kaifu' },
  { code: '43059', name: '长沙雨花区', alias: 'changsha yuhua' },
  // 江西
  { code: '36019', name: '南昌东湖区', alias: 'nanchang donghu' },
  { code: '36029', name: '南昌西湖区', alias: 'nanchang xihu' },
  { code: '36039', name: '南昌青云谱区', alias: 'nanchang qingyunpu' },
  { code: '36049', name: '南昌湾里区', alias: 'nanchang wanli' },
  { code: '36059', name: '南昌青山湖区', alias: 'nanchang qingshanhu' },
  // 广西
  { code: '45019', name: '南宁兴宁区', alias: 'nanning xingning' },
  { code: '45029', name: '南宁青秀区', alias: 'nanning qingxiu' },
  { code: '45039', name: '南宁江南区', alias: 'nanning jiangnan' },
  { code: '45049', name: '南宁西乡塘区', alias: 'nanning xixiangtang' },
  { code: '45059', name: '南宁良庆区', alias: 'nanning liangqing' },
  { code: '45069', name: '南宁邕宁区', alias: 'nanning yongning' },
  { code: '45079', name: '南宁武鸣区', alias: 'nanning wuming' },
  { code: '45109', name: '柳州城中区', alias: 'liuzhou chengzhong' },
  { code: '45209', name: '桂林秀峰区', alias: 'guilin xiufeng' },
  { code: '45309', name: '梧州万秀区', alias: 'wuzhou wanxiu' },
  { code: '45409', name: '北海海城区', alias: 'beihai haicheng' },
  { code: '45509', name: '防城港港口区', alias: 'fangchenggang gangkou' },
  { code: '45609', name: '钦州钦南区', alias: 'qinzhou qinnan' },
  // 云南、贵州
  { code: '53019', name: '昆明五华区', alias: 'kunming wuhua' },
  { code: '52019', name: '贵阳南明区', alias: 'guiyang nanming' },
  // 海南
  { code: '46019', name: '海口秀英区', alias: 'haikou xiuying' },
  { code: '46029', name: '海口龙华区', alias: 'haikou longhua' },
  { code: '46039', name: '海口琼山区', alias: 'haikou qiongshan' },
  { code: '46049', name: '海口美兰区', alias: 'haikou meilan' },
  { code: '46909', name: '海南洋浦保税港区', alias: 'hainan yangpu' },
];
