import type { CustomsCodeItem } from './types';

/**
 * 港口/口岸代码（5位）- 二手车出口常用港口
 * 数据来源：海关《港口代码表》UN/LOCODE
 *
 * 指运港（destinationPort）可为目的国家级聚合代码（如 BGR000 保加利亚），
 * 离境口岸（departurePort）通常为中国境内具体口岸。
 */
export const PORTS: CustomsCodeItem[] = [
  // 中国沿海港口（离境用）
  { code: 'CNSHK', name: '上海港', alias: 'shanghai port shanghaigang', group: '中国港口' },
  { code: 'CNNGB', name: '宁波舟山港', alias: 'ningbo zhoushan port', group: '中国港口' },
  { code: 'CNSNZ', name: '深圳港(蛇口)', alias: 'shenzhen shekou', group: '中国港口' },
  { code: 'CNYTN', name: '深圳港(盐田)', alias: 'shenzhen yantian', group: '中国港口' },
  { code: 'CNCAN', name: '广州港', alias: 'guangzhou port guangzhougang', group: '中国港口' },
  { code: 'CNNSA', name: '南沙港', alias: 'nansha port nanshagang', group: '中国港口' },
  { code: 'CNXMN', name: '厦门港', alias: 'xiamen port xiamengang', group: '中国港口' },
  { code: 'CNFQG', name: '福州港', alias: 'fuzhou port fuzhougang', group: '中国港口' },
  { code: 'CNQIN', name: '青岛港', alias: 'qingdao port qingdaogang', group: '中国港口' },
  { code: 'CNYTI', name: '烟台港', alias: 'yantai port yantaigang', group: '中国港口' },
  { code: 'CNWEH', name: '威海港', alias: 'weihai port weihai gang', group: '中国港口' },
  { code: 'CNTAO', name: '青岛前湾港', alias: 'qingdao qianwan', group: '中国港口' },
  { code: 'CNTSN', name: '天津港', alias: 'tianjin port tianjingang', group: '中国港口' },
  { code: 'CNTXG', name: '天津新港', alias: 'tianjin xingang', group: '中国港口' },
  { code: 'CNDLC', name: '大连港', alias: 'dalian port dalian gang', group: '中国港口' },
  { code: 'CNYIK', name: '营口港', alias: 'yingkou port yingkougang', group: '中国港口' },
  { code: 'CNJNZ', name: '锦州港', alias: 'jinzhou port jinzhougang', group: '中国港口' },
  { code: 'CNLYG', name: '连云港', alias: 'lianyungang port', group: '中国港口' },
  { code: 'CNSHA', name: '上海外高桥', alias: 'shanghai waigaoqiao', group: '中国港口' },
  { code: 'CNPOS', name: '上海洋山港', alias: 'shanghai yangshan', group: '中国港口' },
  { code: 'CNZHE', name: '舟山港', alias: 'zhoushan port zhoushangang', group: '中国港口' },
  { code: 'CNWZH', name: '温州港', alias: 'wenzhou port wenzhougang', group: '中国港口' },
  { code: 'CNSTG', name: '汕头港', alias: 'shantou port shantougang', group: '中国港口' },
  { code: 'CNZHG', name: '湛江港', alias: 'zhanjiang port zhanjiangang', group: '中国港口' },
  { code: 'CNFNG', name: '防城港', alias: 'fangchenggang port', group: '中国港口' },
  { code: 'CNQZH', name: '钦州港', alias: 'qinzhou port qinzhougang', group: '中国港口' },
  { code: 'CNBHY', name: '北海港', alias: 'beihai port beihaigang', group: '中国港口' },
  { code: 'CNHAK', name: '海口港', alias: 'haikou port haikougang', group: '中国港口' },
  { code: 'CNSYX', name: '三亚港', alias: 'sanya port sanyagang', group: '中国港口' },
  { code: 'CNYPG', name: '洋浦港', alias: 'yangpu port yangpugang', group: '中国港口' },
  // 公路/铁路口岸
  { code: 'CNHUG', name: '皇岗口岸(公路)', alias: 'huanggang landport', group: '中国口岸' },
  { code: 'CNWJD', name: '文锦渡口岸', alias: 'wenjindu port', group: '中国口岸' },
  { code: 'CNSBJ', name: '沙头角口岸', alias: 'shatoujiao port', group: '中国口岸' },
  { code: 'CNSZW', name: '深圳湾口岸', alias: 'shenzhenwan port', group: '中国口岸' },
  { code: 'CNLPZ', name: '莲塘口岸', alias: 'liantang port', group: '中国口岸' },
  { code: 'CNGZG', name: '港珠澳大桥口岸', alias: 'hzmb port gangzhuao daqiao', group: '中国口岸' },
  { code: 'CNHEN', name: '横琴口岸', alias: 'hengqin port', group: '中国口岸' },
  { code: 'CNNAN', name: '凭祥口岸(友谊关)', alias: 'pingxiang youyiguan', group: '中国口岸' },
  { code: 'CNDXZ', name: '东兴口岸', alias: 'dongxing port', group: '中国口岸' },
  { code: 'CNMLN', name: '满洲里口岸', alias: 'manzhouli port', group: '中国口岸' },
  { code: 'CNERL', name: '二连浩特口岸', alias: 'erenhot port erlian haote', group: '中国口岸' },
  { code: 'CNALK', name: '阿拉山口口岸', alias: 'alashankou port', group: '中国口岸' },
  { code: 'CNKHG', name: '霍尔果斯口岸', alias: 'khorgos port huoerguosi', group: '中国口岸' },
  { code: 'CNKAS', name: '喀什口岸', alias: 'kashgar port kashi', group: '中国口岸' },
  // 目的港/国家级聚合代码（常见于"指运港"字段）
  { code: 'BGR000', name: '保加利亚', alias: 'bulgaria', group: '国家聚合(指运港)' },
  { code: 'RUS000', name: '俄罗斯联邦', alias: 'russia eluosi', group: '国家聚合(指运港)' },
  { code: 'KAZ000', name: '哈萨克斯坦', alias: 'kazakhstan hasakesitan', group: '国家聚合(指运港)' },
  { code: 'KGZ000', name: '吉尔吉斯斯坦', alias: 'kyrgyzstan', group: '国家聚合(指运港)' },
  { code: 'UZB000', name: '乌兹别克斯坦', alias: 'uzbekistan', group: '国家聚合(指运港)' },
  { code: 'TJK000', name: '塔吉克斯坦', alias: 'tajikistan', group: '国家聚合(指运港)' },
  { code: 'TKM000', name: '土库曼斯坦', alias: 'turkmenistan', group: '国家聚合(指运港)' },
  { code: 'MNG000', name: '蒙古', alias: 'mongolia menggu', group: '国家聚合(指运港)' },
  { code: 'VNM000', name: '越南', alias: 'vietnam yuenan', group: '国家聚合(指运港)' },
  { code: 'LAO000', name: '老挝', alias: 'laos laowo', group: '国家聚合(指运港)' },
  { code: 'KHM000', name: '柬埔寨', alias: 'cambodia jianpuzhai', group: '国家聚合(指运港)' },
  { code: 'MMR000', name: '缅甸', alias: 'myanmar miandian', group: '国家聚合(指运港)' },
  { code: 'THA000', name: '泰国', alias: 'thailand taiguo', group: '国家聚合(指运港)' },
  { code: 'MYS000', name: '马来西亚', alias: 'malaysia malaixiya', group: '国家聚合(指运港)' },
  { code: 'IDN000', name: '印度尼西亚', alias: 'indonesia yinni', group: '国家聚合(指运港)' },
  { code: 'PHL000', name: '菲律宾', alias: 'philippines feilvbin', group: '国家聚合(指运港)' },
  { code: 'ARE000', name: '阿联酋', alias: 'uae united arab emirates', group: '国家聚合(指运港)' },
  { code: 'SAU000', name: '沙特阿拉伯', alias: 'saudi arabia shate', group: '国家聚合(指运港)' },
  { code: 'NGA000', name: '尼日利亚', alias: 'nigeria niriliya', group: '国家聚合(指运港)' },
  { code: 'ZAF000', name: '南非', alias: 'south africa nanfei', group: '国家聚合(指运港)' },
  { code: 'EGY000', name: '埃及', alias: 'egypt aiji', group: '国家聚合(指运港)' },
  { code: 'KEN000', name: '肯尼亚', alias: 'kenya kenniya', group: '国家聚合(指运港)' },
  { code: 'TZA000', name: '坦桑尼亚', alias: 'tanzania tansangniya', group: '国家聚合(指运港)' },
  { code: 'CHL000', name: '智利', alias: 'chile zhili', group: '国家聚合(指运港)' },
  { code: 'PER000', name: '秘鲁', alias: 'peru milu', group: '国家聚合(指运港)' },
  { code: 'MEX000', name: '墨西哥', alias: 'mexico moxige', group: '国家聚合(指运港)' },
  { code: 'PAN000', name: '巴拿马', alias: 'panama banama', group: '国家聚合(指运港)' },
  { code: 'CUB000', name: '古巴', alias: 'cuba guba', group: '国家聚合(指运港)' },
  { code: 'DOM000', name: '多米尼加', alias: 'dominican duominijia', group: '国家聚合(指运港)' },
  { code: 'JAM000', name: '牙买加', alias: 'jamaica yamaijia', group: '国家聚合(指运港)' },
  // 重点海外港口（具体港口）
  { code: 'AEDXB', name: '迪拜港', alias: 'dubai port dibei', group: '海外港口' },
  { code: 'AEJEA', name: '杰贝阿里港', alias: 'jebel ali', group: '海外港口' },
  { code: 'SAJED', name: '吉达港', alias: 'jeddah islamic port', group: '海外港口' },
  { code: 'SADMM', name: '达曼港', alias: 'dammam king abdulaziz', group: '海外港口' },
  { code: 'SGSIN', name: '新加坡港', alias: 'singapore port xinjiapo', group: '海外港口' },
  { code: 'MYTPP', name: '巴生港', alias: 'port klang basheng', group: '海外港口' },
  { code: 'THLCH', name: '林查班港', alias: 'laem chabang', group: '海外港口' },
  { code: 'VNSGN', name: '胡志明港', alias: 'ho chi minh city saigon', group: '海外港口' },
  { code: 'VNHPH', name: '海防港', alias: 'haiphong port haifang', group: '海外港口' },
  { code: 'KHKOS', name: '西哈努克港', alias: 'sihanoukville sihanuke', group: '海外港口' },
  { code: 'IDJKT', name: '雅加达港', alias: 'jakarta tanjung priok', group: '海外港口' },
  { code: 'IDSRG', name: '泗水港', alias: 'surabaya', group: '海外港口' },
  { code: 'PHMNL', name: '马尼拉港', alias: 'manila port', group: '海外港口' },
  { code: 'PHCEB', name: '宿务港', alias: 'cebu port suwu', group: '海外港口' },
  { code: 'NGAPP', name: '阿帕帕港', alias: 'apapa lagos', group: '海外港口' },
  { code: 'NGTIN', name: '廷坎港', alias: 'tin can island lagos', group: '海外港口' },
  { code: 'ZADUR', name: '德班港', alias: 'durban port deban', group: '海外港口' },
  { code: 'ZACPT', name: '开普敦港', alias: 'cape town kaipudun', group: '海外港口' },
  { code: 'EGALY', name: '亚历山大港', alias: 'alexandria yalishanda', group: '海外港口' },
  { code: 'EGPSD', name: '塞得港', alias: 'port said saidegang', group: '海外港口' },
  { code: 'KEMBA', name: '蒙巴萨港', alias: 'mombasa port mengbasa', group: '海外港口' },
  { code: 'TZDAR', name: '达累斯萨拉姆港', alias: 'dar es salaam daleisi', group: '海外港口' },
  { code: 'CLVAP', name: '瓦尔帕莱索港', alias: 'valparaiso waerpalaiao', group: '海外港口' },
  { code: 'CLIQQ', name: '伊基克港', alias: 'iquique yijike', group: '海外港口' },
  { code: 'CLCNL', name: '圣安东尼奥港', alias: 'san antonio shengandongnio', group: '海外港口' },
  { code: 'PECLL', name: '卡亚俄港', alias: 'callao port kayae', group: '海外港口' },
  { code: 'PEPAY', name: '派塔港', alias: 'paita paita', group: '海外港口' },
  { code: 'MXZLO', name: '曼萨尼约港', alias: 'manzanillo mansaniyo', group: '海外港口' },
  { code: 'MXLZC', name: '拉萨罗卡德纳斯', alias: 'lazaro cardenas', group: '海外港口' },
  { code: 'MXVER', name: '韦拉克鲁斯港', alias: 'veracruz weilakelusi', group: '海外港口' },
  { code: 'PABLB', name: '巴尔博亚港', alias: 'balboa baerboya', group: '海外港口' },
  { code: 'PAONX', name: '克里斯托瓦尔港', alias: 'cristobal', group: '海外港口' },
  { code: 'RULED', name: '圣彼得堡港', alias: 'saint petersburg shengbidebao', group: '海外港口' },
  { code: 'RUVVO', name: '符拉迪沃斯托克港', alias: 'vladivostok haishenwai', group: '海外港口' },
  { code: 'RUVYP', name: '东方港', alias: 'vostochny port dongfanggang', group: '海外港口' },
  { code: 'KZAKX', name: '阿克套港', alias: 'aktau port aketao', group: '海外港口' },
  { code: 'TRAMB', name: '安巴尔利港', alias: 'ambarli istanbul', group: '海外港口' },
  { code: 'TRISL', name: '伊斯坦布尔港', alias: 'istanbul port yisitanbuer', group: '海外港口' },
  { code: 'GRPIR', name: '比雷埃夫斯港', alias: 'piraeus athens bileiaifusi', group: '海外港口' },
  { code: 'NLRTM', name: '鹿特丹港', alias: 'rotterdam lutedan', group: '海外港口' },
  { code: 'DEHAM', name: '汉堡港', alias: 'hamburg hanbao', group: '海外港口' },
  { code: 'BEANR', name: '安特卫普港', alias: 'antwerp anteweipu', group: '海外港口' },
  { code: 'ESBCN', name: '巴塞罗那港', alias: 'barcelona basailuona', group: '海外港口' },
  { code: 'ITGOA', name: '热那亚港', alias: 'genoa reshenaya', group: '海外港口' },
  { code: 'USBAL', name: '巴尔的摩港', alias: 'baltimore baerdimo', group: '海外港口' },
  { code: 'USLAX', name: '洛杉矶港', alias: 'los angeles luoshanji', group: '海外港口' },
  { code: 'USLGB', name: '长滩港', alias: 'long beach changtan', group: '海外港口' },
  { code: 'USNYC', name: '纽约港', alias: 'new york niuyue', group: '海外港口' },
  { code: 'USOAK', name: '奥克兰港', alias: 'oakland aokelan', group: '海外港口' },
  { code: 'AUSYD', name: '悉尼港', alias: 'sydney xini', group: '海外港口' },
  { code: 'AUMEL', name: '墨尔本港', alias: 'melbourne miber en', group: '海外港口' },
  { code: 'AUBRH', name: '布里斯班港', alias: 'brisbane bulisiban', group: '海外港口' },
  { code: 'NZAKL', name: '奥克兰港', alias: 'auckland aokelan nz', group: '海外港口' },
  { code: 'JPTYO', name: '东京港', alias: 'tokyo dongjing', group: '海外港口' },
  { code: 'JPYOK', name: '横滨港', alias: 'yokohama hengbin', group: '海外港口' },
  { code: 'JPOSA', name: '大阪港', alias: 'osaka daban', group: '海外港口' },
  { code: 'KRPUS', name: '釜山港', alias: 'busan fushan', group: '海外港口' },
  { code: 'KRINC', name: '仁川港', alias: 'incheon renchuan', group: '海外港口' },
  { code: 'HKHKG', name: '香港', alias: 'hong kong xianggang', group: '海外港口' },
  { code: 'TWKHH', name: '高雄港', alias: 'kaohsiung gaoxiong', group: '海外港口' },
  { code: 'TWKEL', name: '基隆港', alias: 'keelung jilong', group: '海外港口' },
  { code: 'BDCGP', name: '吉大港', alias: 'chittagong jidagang', group: '海外港口' },
  { code: 'INMAA', name: '钦奈港', alias: 'chennai madras qinnai', group: '海外港口' },
  { code: 'INNSA', name: '孟买新港', alias: 'nhava sheva mumbai', group: '海外港口' },
  { code: 'PKKHI', name: '卡拉奇港', alias: 'karachi kalaqi', group: '海外港口' },
  { code: 'LKGAL', name: '加勒港', alias: 'galle port', group: '海外港口' },
  { code: 'IRBND', name: '阿巴斯港', alias: 'bandar abbas abasi', group: '海外港口' },
  { code: 'OMSLL', name: '塞拉莱港', alias: 'salalah port salale', group: '海外港口' },
  { code: 'CHBSL', name: '巴塞尔港', alias: 'basel port basier', group: '海外港口' },
];
